import { all_routes } from "../../../feature-module/routes/all_routes";

const routes = all_routes;

// Helper function to get role-specific sidebar data
export const getSidebarDataByRole = (role?: string) => {
  if (role === "super_admin") {
    return SuperAdminSidebarData;
  } else if (role === "hospital_admin") {
    return HospitalAdminSidebarData;
  } else if (role === "doctor") {
    return DoctorSidebarData;
  }
  // Default/Admin sidebar
  return AdminSidebarData;
};

// Super Admin Sidebar Data - Full access to all branches
const SuperAdminSidebarData = [
  {
    tittle: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.superAdminDashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Branches",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Hospitals",
        link: routes.hospitals,
        submenu: false,
        showSubRoute: false,
        icon: "building-hospital",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Add Hospital",
        link: routes.addHospital,
        submenu: false,
        showSubRoute: false,
        icon: "plus",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },

  {
    tittle: "Finance & Accounts",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Expenses",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "credit-card",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Expenses", link: routes.expenses },
          { label: "Expense Category", link: routes.expenseCategory },
        ],
      },
      {
        label: "Income",
        link: routes.income,
        submenu: false,
        showSubRoute: false,
        icon: "coins",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Invoices",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "file-invoice",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Invoices", link: routes.invoices },
          { label: "Invoice Details", link: routes.invoiceDetails },
        ],
      },
      {
        label: "Payments",
        link: routes.payments,
        submenu: false,
        showSubRoute: false,
        icon: "cards",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Transactions",
        link: routes.transactions,
        submenu: false,
        showSubRoute: false,
        icon: "transition-right",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Settings",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Account Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "user-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Profile",
            link: routes.profilesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Security",
            link: routes.securitysettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Notifications",
            link: routes.notificationssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Integrations",
            link: routes.integrationssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Clinic Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "building-hospital",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Appointment",
            link: routes.appointmentsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Working Hours",
            link: routes.workinghourssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Cancellation Reason",
            link: routes.cancellationreasonsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "App Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "device-mobile-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Invoice Settings",
            link: routes.invoicesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Invoice Templates",
            link: routes.invoicetemplatessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Signatures",
            link: routes.signaturessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Custom Fields",
            link: routes.customfieldssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
    ],
  },
];

// Hospital Admin Sidebar Data - Manage their own hospital branch
const HospitalAdminSidebarData = [
  {
    tittle: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.dashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Clinic",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Doctors",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-plus",
        base: "Doctors",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Doctors", link: routes.doctors },
          { label: "Add Doctor", link: routes.addDoctors },
          // { label: "Doctor Schedule", link: routes.doctorScheduleClini },
        ],
      },
      {
        label: "Patients",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-heart",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Patients", link: routes.patients },
        ],
      },
      {
        label: "Appointments",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "calendar-check",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Appointments", link: routes.appointments },
          { label: "New Appointment", link: routes.newAppointment },
          { label: "Calendar", link: routes.appointmentCalendar },
        ],
      },
      // {
      //   label: "Locations",
      //   link: routes.locations,
      //   submenu: false,
      //   showSubRoute: false,
      //   icon: "map-pin",
      //   base: "frontent",
      //   materialicons: "start",
      //   dot: true,
      //   submenuItems: [],
      // },
      // {
      //   label: "Services",
      //   link: routes.services,
      //   submenu: false,
      //   showSubRoute: false,
      //   icon: "map-pin",
      //   base: "frontent",
      //   materialicons: "start",
      //   dot: true,
      //   submenuItems: [],
      // },
      // {
      //   label: "specializations",
      //   link: routes.specializations,
      //   submenu: false,
      //   showSubRoute: false,
      //   icon: "user-shield",
      //   base: "frontent",
      //   materialicons: "start",
      //   dot: true,
      //   submenuItems: [],
      // },
      {
        label: "Inventory",
        link: routes.inventory,
        submenu: false,
        showSubRoute: false,
        icon: "package",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "GRN",
        link: routes.grn,
        submenu: false,
        showSubRoute: false,
        icon: "file-invoice",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Pharmacy",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "pills",
        base: "Pharmacy",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Pharmacies", link: routes.pharmacies },
          { label: "Add Pharmacy User", link: routes.addPharmacy },
        ],
      },
    ],
  },
  {
    tittle: "Finance & Accounts",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Expenses",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "credit-card",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Expenses", link: routes.expenses },
          { label: "Expense Category", link: routes.expenseCategory },
        ],
      },
      {
        label: "Income",
        link: routes.income,
        submenu: false,
        showSubRoute: false,
        icon: "coins",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Invoices",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "file-invoice",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Invoices", link: routes.invoices },
          { label: "Invoice Details", link: routes.invoiceDetails },
        ],
      },
      {
        label: "Payments",
        link: routes.payments,
        submenu: false,
        showSubRoute: false,
        icon: "cards",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Transactions",
        link: routes.transactions,
        submenu: false,
        showSubRoute: false,
        icon: "transition-right",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Settings",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Account Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "user-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Profile",
            link: routes.profilesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Security",
            link: routes.securitysettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Notifications",
            link: routes.notificationssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Integrations",
            link: routes.integrationssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "Clinic Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "building-hospital",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Appointment",
            link: routes.appointmentsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Working Hours",
            link: routes.workinghourssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Cancellation Reason",
            link: routes.cancellationreasonsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      {
        label: "App Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "device-mobile-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Invoice Settings",
            link: routes.invoicesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Invoice Templates",
            link: routes.invoicetemplatessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Signatures",
            link: routes.signaturessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Custom Fields",
            link: routes.customfieldssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
    ],
  },
];

// Doctor Sidebar Data - Limited access for doctors
const DoctorSidebarData = [
  {
    tittle: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.doctordashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "My Practice",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Appointments",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "calendar-check",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "My Appointments", link: routes.doctorsappointments },
          { label: "Online Consultations", link: routes.onlineconsultations },
        ],
      },
      {
        label: "Patients",
        link: routes.doctorspatientdetails,
        submenu: false,
        showSubRoute: false,
        icon: "user-heart",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Prescriptions",
        link: routes.doctorsprescriptions,
        submenu: false,
        showSubRoute: false,
        icon: "file-prescription",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Schedule",
        link: routes.doctorschedule,
        submenu: false,
        showSubRoute: false,
        icon: "calendar",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Leaves",
        link: routes.doctorleaves,
        submenu: false,
        showSubRoute: false,
        icon: "users-minus",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Reviews",
        link: routes.doctorreviews,
        submenu: false,
        showSubRoute: false,
        icon: "star",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  {
    tittle: "Settings",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Account Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "user-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Profile",
            link: routes.doctorsprofilesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Security",
            link: routes.doctorspasswordsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Notifications",
            link: routes.doctorsnotificationsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
    ],
  },
];

// Admin Sidebar Data (default - for admin, receptionist, etc.)
const AdminSidebarData = [
  {
   tittle: "Main Menu",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Dashboard",
        link: routes.superAdminDashboard,
        submenu: false,
        showSubRoute: false,
        icon: "layout-dashboard",
        base: "dashboard",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      // {
      //   label: "Applications",
      //   link: "index",
      //   submenu: true,
      //   showSubRoute: false,
      //   icon: "apps",
      //   base: "dashboard",
      //   materialicons: "start",
      //   dot: true,
      //   submenuItems: [
      //     { label: "Chat", link: routes.chat },
      //     {
      //       label: "Calls",
      //       customSubmenuTwo: true,
      //       submenu: true,
      //       showSubRoute: false,
      //       link: routes.voiceCall,
      //       page1: "voice-call",
      //       page2: "videocall",
      //       base: "calls",
      //       submenuItems: [
      //         {
      //           label: "Voice Call",
      //           link: routes.voiceCall,
      //           submenu: false,
      //           showSubRoute: false,
      //           base: "voice-call",
      //         },
      //         {
      //           label: "Video Call",
      //           link: routes.videoCall,
      //           submenu: false,
      //           showSubRoute: false,
      //           base: "video-call",
      //         },
      //         {
      //           label: "Outgoing Call",
      //           link: routes.outgoingCall,
      //           submenu: false,
      //           showSubRoute: false,
      //           base: "outgoing-call",
      //         },
      //         {
      //           label: "Incoming Call",
      //           link: routes.incomingCall,
      //           submenu: false,
      //           showSubRoute: false,
      //           base: "incoming-call",
      //         },
      //         {
      //           label: "Call History",
      //           link: routes.callHistory,
      //           submenu: false,
      //           showSubRoute: false,
      //           base: "call-history",
      //         },
      //       ],
      //     },
      //     {
      //       label: "Calendar",
      //       showSubRoute: false,
      //       link: routes.calendar,
      //       customSubmenuTwo: false,
      //       base: "calendar",
      //     },
      //     {
      //       label: "Contacts",
      //       showSubRoute: false,
      //       link: routes.contacts,
      //       customSubmenuTwo: false,
      //       base: "kanban",
      //     },

      //     {
      //       label: "Email",
      //       showSubRoute: false,
      //       link: routes.email,
      //       customSubmenuTwo: false,
      //       base: "email",
      //     },
      //     {
      //       label: "Invoices",
      //       customSubmenuTwo: true,
      //       submenu: true,
      //       showSubRoute: false,
      //       link: routes.voiceCall,
      //       page1: "Invoices",
      //       page2: "Invoice Details",
      //       base: "calls",
      //       submenuItems: [
      //         {
      //           label: "Invoices",
      //           link: routes.invoice,
      //           submenu: false,
      //           showSubRoute: false,
      //           base: "voice-call",
      //         },
      //         {
      //           label: "Invoice Details",
      //           link: routes.invoiceDetails,
      //           submenu: false,
      //           showSubRoute: false,
      //           base: "video-call",
      //         },
      //       ],
      //     },
      //     {
      //       label: "To Do",
      //       showSubRoute: false,
      //       link: routes.todo,
      //       customSubmenuTwo: false,
      //       base: "todo",
      //     },
      //     {
      //       label: "Notes",
      //       showSubRoute: false,
      //       link: routes.notes,
      //       customSubmenuTwo: false,
      //       base: "notes",
      //     },
      //     {
      //       label: "Kanban Board",
      //       showSubRoute: false,
      //       link: routes.kanbanView,
      //       customSubmenuTwo: false,
      //       base: "kanban",
      //     },
      //     {
      //       label: "File Manager",
      //       showSubRoute: false,
      //       link: routes.fileManager,
      //       customSubmenuTwo: false,
      //       base: "file-manager",
      //     },

      //     {
      //       label: "Social Feed",
      //       showSubRoute: false,
      //       link: routes.socialFeed,
      //       customSubmenuTwo: false,
      //       base: "social-feed",
      //     },

      //     {
      //       label: "Search Result",
      //       showSubRoute: false,
      //       link: routes.searchList,
      //       customSubmenuTwo: false,
      //       base: "invoices",
      //     },
      //   ],
      // },
      // {
      //   label: "Layouts",
      //   link: "index",
      //   submenu: true,
      //   showSubRoute: false,
      //   icon: "layout-sidebar",
      //   base: "dashboard",
      //   materialicons: "start",
      //   dot: true,
      //   submenuItems: [
      //     {
      //       label: "Default",
      //       showSubRoute: false,
      //       link: routes.layoutDefault,
      //       customSubmenuTwo: false,
      //       base: "Default",
      //     },

      //     {
      //       label: "Mini",
      //       showSubRoute: false,
      //       link: routes.layoutMini,
      //       customSubmenuTwo: false,
      //       base: "Mini",
      //     },
      //     {
      //       label: "Hover View",
      //       showSubRoute: false,
      //       link: routes.layoutHoverView,
      //       customSubmenuTwo: false,
      //       base: "Hover View",
      //     },
      //     {
      //       label: "Hidden",
      //       showSubRoute: false,
      //       link: routes.layoutHidden,
      //       customSubmenuTwo: false,
      //       base: "Hidden",
      //     },
      //     {
      //       label: "Full Width",
      //       showSubRoute: false,
      //       link: routes.layoutFullWidth,
      //       customSubmenuTwo: false,
      //       base: "Full Width",
      //     },
      //     {
      //       label: "Dark",
      //       showSubRoute: false,
      //       link: routes.layoutDark,
      //       customSubmenuTwo: false,
      //       base: "dark",
      //     },
      //     {
      //       label: "RTL",
      //       showSubRoute: false,
      //       link: routes.layoutRTL,
      //       customSubmenuTwo: false,
      //       base: "RTL",
      //     },
      //   ],
      // },
    ],
  },
  {
    tittle: "Clinic",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Doctors",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-plus",
        base: "Doctors",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Doctors", link: routes.doctors },
          // { label: "Doctor Details", link: routes.doctorsDetails },
          { label: "Add Doctor", link: routes.addDoctors },
          { label: "Doctor Schedule", link: routes.doctorScheduleClini },
        ],
      },
      {
        label: "Patients",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "user-heart",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Patients", link: routes.patients },
          // { label: "Patient Details", link: routes.patientDetails },
          // { label: "Create Patient", link: routes.createPatient },
        ],
      },
      {
        label: "Appointments",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "calendar-check",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Appointments", link: routes.appointments },
          { label: "New Appointment", link: routes.newAppointment },
          { label: "Calendar", link: routes.appointmentCalendar },
        ],
      },
      {
        label: "Locations",
        link: routes.locations,
        submenu: false,
        showSubRoute: false,
        icon: "map-pin",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Services",
        link: routes.services,
        submenu: false,
        showSubRoute: false,
        icon: "map-pin",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "specializations",
        link: routes.specializations,
        submenu: false,
        showSubRoute: false,
        icon: "user-shield",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Inventory",
        link: routes.inventory,
        submenu: false,
        showSubRoute: false,
        icon: "package",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "GRN",
        link: routes.grn,
        submenu: false,
        showSubRoute: false,
        icon: "file-invoice",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Hospitals",
        link: routes.hospitals,
        submenu: false,
        showSubRoute: false,
        icon: "building-hospital",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
        roles: ["super_admin"], // Only show for super_admin
      },

      // {
      //   label: "Assets",
      //   link: routes.assets,
      //   submenu: false,
      //   showSubRoute: false,
      //   icon: "asset",
      //   base: "frontent",
      //   materialicons: "start",
      //   dot: true,
      //   submenuItems: [],
      // },
      // {
      //   label: "Activities",
      //   link: routes.activities,
      //   submenu: false,
      //   showSubRoute: false,
      //   icon: "activity",
      //   base: "frontent",
      //   materialicons: "start",
      //   dot: true,
      //   submenuItems: [],
      // },
      // {
      //   label: "Messages",
      //   link: routes.messages,
      //   submenu: false,
      //   showSubRoute: false,
      //   icon: "messages",
      //   base: "frontent",
      //   materialicons: "start",
      //   dot: true,
      //   submenuItems: [],
      // },
    ],
  },
  // {
  //   tittle: "HRM",
  //   icon: "airplay",
  //   showAsTab: true,
  //   separateRoute: false,
  //   submenuItems: [
  //     {
  //       label: "Staffs",
  //       link: routes.staffs,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "users-group",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Departments",
  //       link: routes.hrmDepartments,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "building-bank",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Designation",
  //       link: routes.designation,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "user-cog",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },

  //     {
  //       label: "Attendance",
  //       link: routes.attendance,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "user-check",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Activities",
  //       link: routes.activities,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "activity",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Leaves",
  //       link: "index",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "users-minus",
  //       base: "Patients",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [
  //         { label: "Leaves", link: routes.leaves },
  //         { label: "Leave Type", link: routes.leaveType },
  //       ],
  //     },
  //     {
  //       label: "Holidays",
  //       link: routes.holidays,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "home-exclamation",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Payroll",
  //       link: routes.payroll,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "coin",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //   ],
  // },
  {
    tittle: "Finance & Accounts",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Expenses",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "credit-card",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Expenses", link: routes.expenses },
          { label: "Expense Category", link: routes.expenseCategory },
        ],
      },
      {
        label: "Income",
        link: routes.income,
        submenu: false,
        showSubRoute: false,
        icon: "coins",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Invoices",
        link: "index",
        submenu: true,
        showSubRoute: false,
        icon: "file-invoice",
        base: "Patients",
        materialicons: "start",
        dot: true,
        submenuItems: [
          { label: "Invoices", link: routes.invoices },
          { label: "Invoice Details", link: routes.invoiceDetails },
        ],
      },
      {
        label: "Payments",
        link: routes.payments,
        submenu: false,
        showSubRoute: false,
        icon: "cards",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
      {
        label: "Transactions",
        link: routes.transactions,
        submenu: false,
        showSubRoute: false,
        icon: "transition-right",
        base: "frontent",
        materialicons: "start",
        dot: true,
        submenuItems: [],
      },
    ],
  },
  // {
  //   tittle: "Administration",
  //   icon: "airplay",
  //   showAsTab: true,
  //   separateRoute: false,
  //   submenuItems: [
  //     {
  //       label: "Users",
  //       link: "index",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "user",
  //       base: "Users",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [
  //         { label: "Roles & Permissions", link: routes.rolesPermissions },
  //         {
  //           label: "Delete Account Request",
  //           link: routes.deleteaccountrequest,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Reports",
  //       link: "index",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "report",
  //       base: "Users",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [
  //         { label: "Income Report", link: routes.incomeReport },
  //         { label: "Expense Report", link: routes.expenseReport },
  //         { label: "Profit & Loss", link: routes.profitloss },
  //         { label: "Appointment Report", link: routes.appointmentReport },
  //         { label: "Patient Report", link: routes.patientReport },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   tittle: "Content",
  //   icon: "airplay",
  //   showAsTab: true,
  //   separateRoute: false,
  //   submenuItems: [
  //     {
  //       label: "Pages",
  //       link: routes.pages,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "brand-pagekit",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Blogs",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "brand-blogger",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Add Blogs",
  //           link: routes.addBlogs,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Blogs",
  //           link: routes.blogs,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Blog Categories",
  //           link: routes.blogCategories,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Blog Comments",
  //           link: routes.blogComments,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Locations",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "map-pins",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Countries",
  //           link: routes.countries,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "States",
  //           link: routes.states,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Cities",
  //           link: routes.cities,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Testimonials",
  //       link: routes.testimonials,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "brand-wechat",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "FAQ’S",
  //       link: routes.faq,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "question-mark",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //   ],
  // },
  // {
  //   tittle: "Support",
  //   icon: "airplay",
  //   showAsTab: true,
  //   separateRoute: false,
  //   submenuItems: [
  //     {
  //       label: "Contact Messages",
  //       link: routes.contactMessages,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "message-dots",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Tickets",
  //       link: routes.tickets,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "ticket",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Announcements",
  //       link: routes.announcements,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "speakerphone",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Newsletters",
  //       link: routes.newsletters,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "mail-bolt",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //   ],
  // },
  // {
  //   tittle: "Pages",
  //   icon: "airplay",
  //   showAsTab: true,
  //   separateRoute: false,
  //   submenuItems: [
  //     {
  //       label: "Starter",
  //       link: routes.starter,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "player-play",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },

  //     {
  //       label: "Profile",
  //       link: routes.profile,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "user-circle",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },

  //     {
  //       label: "Gallery",
  //       link: routes.gallery,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "photo",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Timeline",
  //       link: routes.timeline,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "timeline-event-text",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Pricing",
  //       link: routes.pricing,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "tag",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },

  //     {
  //       label: "Coming Soon",
  //       link: routes.comingSoon,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "sparkles",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Under Maintenance",
  //       link: routes.underMaintenance,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "settings-down",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Privacy Policy",
  //       link: routes.privacyPolicy,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "shield-check",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Terms & Conditions",
  //       link: routes.termsCondition,
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "file-time",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //   ],
  // },
  // {
  //   tittle: "Authentication",
  //   icon: "airplay",
  //   showAsTab: true,
  //   separateRoute: false,
  //   submenuItems: [
  //     {
  //       label: "Login",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "login",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Cover",
  //           link: routes.loginCover,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Illustration",
  //           link: routes.loginillustration,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Basic",
  //           link: routes.loginbasic,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Register",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "file-pencil",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Cover",
  //           link: routes.registercover,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Illustration",
  //           link: routes.registerillustration,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Basic",
  //           link: routes.registerbasic,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     // {
  //     //   label: "Forgot Password",
  //     //   link: "apps",
  //     //   submenu: true,
  //     //   showSubRoute: false,
  //     //   icon: "lock-exclamation",
  //     //   base: "inventory",
  //     //   materialicons: "dashboard",
  //     //   submenuItems: [
  //     //     {
  //     //       label: "Cover",
  //     //       link: routes.forgotpasswordcover,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "Illustration",
  //     //       link: routes.forgotpasswordillustration,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "Basic",
  //     //       link: routes.forgotpasswordbasic,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //   ],
  //     // },
  //     // {
  //     //   label: "Reset Password",
  //     //   link: "apps",
  //     //   submenu: true,
  //     //   showSubRoute: false,
  //     //   icon: "restore",
  //     //   base: "inventory",
  //     //   materialicons: "dashboard",
  //     //   submenuItems: [
  //     //     {
  //     //       label: "Cover",
  //     //       link: routes.resetpasswordcover,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "Illustration",
  //     //       link: routes.resetpasswordillustration,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "Basic",
  //     //       link: routes.resetpasswordbasic,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //   ],
  //     // },
  //     // {
  //     //   label: "Email Verification",
  //     //   link: "apps",
  //     //   submenu: true,
  //     //   showSubRoute: false,
  //     //   icon: "mail-check",
  //     //   base: "inventory",
  //     //   materialicons: "dashboard",
  //     //   submenuItems: [
  //     //     {
  //     //       label: "Cover",
  //     //       link: routes.emailverificationcover,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "Illustration",
  //     //       link: routes.emailverificationillustration,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "Basic",
  //     //       link: routes.emailverificationbasic,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //   ],
  //     // },
  //     // {
  //     //   label: "2 Step Verification",
  //     //   link: "apps",
  //     //   submenu: true,
  //     //   showSubRoute: false,
  //     //   icon: "discount-check",
  //     //   base: "inventory",
  //     //   materialicons: "dashboard",
  //     //   submenuItems: [
  //     //     {
  //     //       label: "Cover",
  //     //       link: routes.twostepverificationcover,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "Illustration",
  //     //       link: routes.twostepverificationillustration,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "Basic",
  //     //       link: routes.twostepverificationbasic,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //   ],
  //     // },
  //     // {
  //     //   label: "Lock Screen",
  //     //   link: routes.lockscreen,
  //     //   submenu: false,
  //     //   showSubRoute: false,
  //     //   icon: "lock",
  //     //   base: "inventory",
  //     //   materialicons: "dashboard",
  //     //   submenuItems: [],
  //     // },
  //     // {
  //     //   label: "Error Pages",
  //     //   link: "apps",
  //     //   submenu: true,
  //     //   showSubRoute: false,
  //     //   icon: "exclamation-mark-off",
  //     //   base: "inventory",
  //     //   materialicons: "dashboard",
  //     //   submenuItems: [
  //     //     {
  //     //       label: "404 Error",
  //     //       link: routes.error404,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //     {
  //     //       label: "500 Error",
  //     //       link: routes.error500,
  //     //       base: "invoices",
  //     //       customSubmenuTwo: false,
  //     //     },
  //     //   ],
  //     // },
  //   ],
  // },
  {
    tittle: "Settings",
    icon: "airplay",
    showAsTab: true,
    separateRoute: false,
    submenuItems: [
      {
        label: "Account Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "user-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Profile",
            link: routes.profilesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Security",
            link: routes.securitysettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Notifications",
            link: routes.notificationssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Integrations",
            link: routes.integrationssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },
      // {
      //   label: "Website Settings",
      //   link: "apps",
      //   submenu: true,
      //   showSubRoute: false,
      //   icon: "world-cog",
      //   base: "inventory",
      //   materialicons: "dashboard",
      //   submenuItems: [
      //     {
      //       label: "Organization",
      //       link: routes.organizationsettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Localization",
      //       link: routes.localizationsettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Prefixes",
      //       link: routes.prefixessettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "SEO Setup",
      //       link: routes.seosetupsettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Language",
      //       link: routes.languagesettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Maintenance Mode",
      //       link: routes.maintenancemodesettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Login & Register",
      //       link: routes.loginandregistersettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Preferences",
      //       link: routes.preferencessettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //   ],
      // },

      {
        label: "Clinic Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "building-hospital",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Appointment",
            link: routes.appointmentsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Working Hours",
            link: routes.workinghourssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Cancellation Reason",
            link: routes.cancellationreasonsettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },

      {
        label: "App Settings",
        link: "apps",
        submenu: true,
        showSubRoute: false,
        icon: "device-mobile-cog",
        base: "inventory",
        materialicons: "dashboard",
        submenuItems: [
          {
            label: "Invoice Settings",
            link: routes.invoicesettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Invoice Templates",
            link: routes.invoicetemplatessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Signatures",
            link: routes.signaturessettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
          {
            label: "Custom Fields",
            link: routes.customfieldssettings,
            base: "invoices",
            customSubmenuTwo: false,
          },
        ],
      },

      // {
      //   label: "System Settings",
      //   link: "apps",
      //   submenu: true,
      //   showSubRoute: false,
      //   icon: "device-desktop-cog",
      //   base: "inventory",
      //   materialicons: "dashboard",
      //   submenuItems: [
      //     {
      //       label: "Email Settings",
      //       link: routes.emailsettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Email Templates",
      //       link: routes.emailtemplatessettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "SMS Gateways",
      //       link: routes.smsgatewayssettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "SMS Templates",
      //       link: routes.smstemplatessettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "GDPR Cookies",
      //       link: routes.gdprcookiessettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //   ],
      // },

      // {
      //   label: "Finance & Accounts",
      //   link: "apps",
      //   submenu: true,
      //   showSubRoute: false,
      //   icon: "settings-dollar",
      //   base: "inventory",
      //   materialicons: "dashboard",
      //   submenuItems: [
      //     {
      //       label: "Payment Methods",
      //       link: routes.paymentmethodssettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Bank Accounts",
      //       link: routes.bankaccountssettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Tax Rates",
      //       link: routes.taxratessettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Currencies",
      //       link: routes.currenciessettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //   ],
      // },

      // {
      //   label: "Other Settings",
      //   link: "apps",
      //   submenu: true,
      //   showSubRoute: false,
      //   icon: "settings-2",
      //   base: "inventory",
      //   materialicons: "dashboard",
      //   submenuItems: [
      //     {
      //       label: "Sitemap",
      //       link: routes.sitemapsettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Clear Cache",
      //       link: routes.clearcachesettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Storage",
      //       link: routes.storagesettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Cronjob",
      //       link: routes.cronjobsettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "Ban IP Address",
      //       link: routes.banipaddresssettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "System Backup",
      //       link: routes.systembackupsettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },

      //     {
      //       label: "Database Backup",
      //       link: routes.databasebackupsettings,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //     {
      //       label: "System Update",
      //       link: routes.systemupdate,
      //       base: "invoices",
      //       customSubmenuTwo: false,
      //     },
      //   ],
      // },
    ],
  },
  // {
  //   tittle: "UI Interface",
  //   icon: "airplay",
  //   showAsTab: true,
  //   separateRoute: false,
  //   submenuItems: [
  //     {
  //       label: "Base UI",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "chart-pie",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Accordion",
  //           link: routes.uiAccordion,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Alerts",
  //           link: routes.uiAlerts,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Avatar",
  //           link: routes.uiAvatar,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Badges",
  //           link: routes.uiBadges,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Breadcrumb",
  //           link: routes.uiBreadcrumb,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Buttons",
  //           link: routes.uiButtons,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Button Group",
  //           link: routes.uiButtonsGroup,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Card",
  //           link: routes.uiCards,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Carousel",
  //           link: routes.uiCarousel,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Collapse",
  //           link: routes.uiCollapse,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Dropdowns",
  //           link: routes.uiDropdowns,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Ratio",
  //           link: routes.uiRatio,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Grid",
  //           link: routes.uiGrid,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Images",
  //           link: routes.uiImages,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Links",
  //           link: routes.uiLinks,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "List Group",
  //           link: routes.uiListGroup,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Modals",
  //           link: routes.uiModals,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Offcanvas",
  //           link: routes.uiOffcanvas,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Pagination",
  //           link: routes.uiPagination,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Placeholders",
  //           link: routes.uiPlaceholders,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Popovers",
  //           link: routes.uiPopovers,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Progress",
  //           link: routes.uiProgress,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Scrollspy",
  //           link: routes.uiScrollspy,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Spinner",
  //           link: routes.uiSpinner,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Tabs",
  //           link: routes.uiNavTabs,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Toasts",
  //           link: routes.uiToasts,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Tooltips",
  //           link: routes.uiTooltips,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Typography",
  //           link: routes.uiTypography,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Utilities",
  //           link: routes.uiUtilities,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Advanced UI",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "radar",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Dragula",
  //           link: routes.dragula,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Clipboard",
  //           link: routes.uiClipboard,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Range Slider",
  //           link: routes.uiRangeslider,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Lightbox",
  //           link: routes.uiLightbox,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Rating",
  //           link: routes.uiRating,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Counter",
  //           link: routes.uiCounter,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Scrollbar",
  //           link: routes.uiScrollbar,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Forms",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "forms",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Form Elements",
  //           link: "apps",
  //           submenu: true,
  //           showSubRoute: false,
  //           base: "inventory",
  //           materialicons: "dashboard",
  //           submenuItems: [
  //             {
  //               label: "Basic Inputs",
  //               link: routes.formBasicInputs,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //             {
  //               label: "Checkbox & Radios",
  //               link: routes.formCheckboxRadios,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //             {
  //               label: "Input Groups",
  //               link: routes.formInputGroups,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //             {
  //               label: "Grid & Gutters",
  //               link: routes.formGridGutters,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //             {
  //               label: "Input Masks",
  //               link: routes.formMask,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //             {
  //               label: "File Uploads",
  //               link: routes.formFileupload,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //           ],
  //         },
  //         {
  //           label: "Layouts",
  //           link: "apps",
  //           submenu: true,
  //           showSubRoute: false,
  //           base: "inventory",
  //           materialicons: "dashboard",
  //           submenuItems: [
  //             {
  //               label: "Horizontal Form",
  //               link: routes.formHorizontal,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //             {
  //               label: "Vertical Form",
  //               link: routes.formVertical,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //             {
  //               label: "Floating Labels",
  //               link: routes.formFloatingLabels,
  //               base: "invoices",
  //               customSubmenuTwo: false,
  //             },
  //           ],
  //         },
  //         {
  //           label: "Form Validation",
  //           link: routes.formValidation,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Select2",
  //           link: routes.formSelect2,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Form Wizard",
  //           link: routes.formWizard,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Form Picker",
  //           link: routes.formPickers,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Tables",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "table-row",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Basic Tables ",
  //           link: routes.tablesBasic,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Data Table ",
  //           link: routes.dataTables,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Charts",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "chart-donut",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Apex Charts",
  //           link: routes.chartApex,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //     {
  //       label: "Icons",
  //       link: "apps",
  //       submenu: true,
  //       showSubRoute: false,
  //       icon: "icons",
  //       base: "inventory",
  //       materialicons: "dashboard",
  //       submenuItems: [
  //         {
  //           label: "Fontawesome Icons",
  //           link: routes.iconFontawesome,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Tabler Icons",
  //           link: routes.iconTabler,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Bootstrap Icons",
  //           link: routes.iconBootstrap,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Remix Icons",
  //           link: routes.iconRemix,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Ionic Icons",
  //           link: routes.iconIonic,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Material Icons",
  //           link: routes.iconMaterial,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Pe7 Icons",
  //           link: routes.iconPe7,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },

  //         {
  //           label: "Themify Icons",
  //           link: routes.iconThemify,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Weather Icons",
  //           link: routes.iconWeather,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Typicon Icons",
  //           link: routes.iconTypicon,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //         {
  //           label: "Flag Icons",
  //           link: routes.iconFlag,
  //           base: "invoices",
  //           customSubmenuTwo: false,
  //         },
  //       ],
  //     },
  //   ],
  // },
  // {
  //   tittle: "Help",
  //   icon: "airplay",
  //   showAsTab: true,
  //   separateRoute: false,
  //   submenuItems: [
  //     {
  //       label: "Documentation",
  //       link: "https://Zaptas.dreamstechnologies.com/documentation/react.html",
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "file-dots",
  //       base: "frontent",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //     {
  //       label: "Changelog",
  //       link: "https://Zaptas.dreamstechnologies.com/documentation/changelog.html",
  //       submenu: false,
  //       showSubRoute: false,
  //       icon: "status-change",
  //       base: "frontent",
  //       version: "v1.7.3",
  //       materialicons: "start",
  //       dot: true,
  //       submenuItems: [],
  //     },
  //   ],
  // },
];

// Export default for backward compatibility (returns AdminSidebarData)
export const SidebarData = AdminSidebarData;
