
import { Link } from 'react-router'
import "../../../../../../style/icon/ionic/ionicons.css"

const IconIonic = () => {
  return (
    <>
  {/* ========================
			Start Page Content
		========================= */}
  <div className="page-wrapper cardhead">
    {/* Start Content */}
    <div className="content">
      {/* Page Header */}
      <div className="page-header">
        <div className="row">
          <div className="col-sm-12">
            <h3 className="page-title">Ionic Icon</h3>
          </div>
        </div>
      </div>
      {/* End Page Header */}
      {/* start row */}
      <div className="row">
        <div className="col-md-12">
          <div className="card">
            <div className="card-header">
              <div className="card-title">Ionic Icon</div>
            </div>
            {/* end card-header */}
            <div className="card-body">
              <div className="icons-items">
                <ul className="icons-list">
                  <li>
                    <i
                      className="ion-ionic"
                      data-bs-toggle="tooltip"
                      title="ion-ionic"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-up-a"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-up-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-right-a"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-right-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-down-a"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-down-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-left-a"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-left-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-up-b"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-up-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-right-b"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-right-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-down-b"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-down-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-left-b"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-left-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-up-c"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-up-c"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-right-c"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-right-c"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-down-c"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-down-c"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-left-c"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-left-c"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-return-right"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-return-right"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-return-left"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-return-left"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-swap"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-swap"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-shrink"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-shrink"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-expand"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-expand"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-move"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-move"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-resize"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-resize"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chevron-up"
                      data-bs-toggle="tooltip"
                      title="ion-chevron-up"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chevron-right"
                      data-bs-toggle="tooltip"
                      title="ion-chevron-right"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chevron-down"
                      data-bs-toggle="tooltip"
                      title="ion-chevron-down"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chevron-left"
                      data-bs-toggle="tooltip"
                      title="ion-chevron-left"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-navicon-round"
                      data-bs-toggle="tooltip"
                      title="ion-navicon-round"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-navicon"
                      data-bs-toggle="tooltip"
                      title="ion-navicon"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-drag"
                      data-bs-toggle="tooltip"
                      title="ion-drag"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-log-in"
                      data-bs-toggle="tooltip"
                      title="ion-log-in"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-log-out"
                      data-bs-toggle="tooltip"
                      title="ion-log-out"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-checkmark-round"
                      data-bs-toggle="tooltip"
                      title="ion-checkmark-round"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-checkmark"
                      data-bs-toggle="tooltip"
                      title="ion-checkmark"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-checkmark-circled"
                      data-bs-toggle="tooltip"
                      title="ion-checkmark-circled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-close-round"
                      data-bs-toggle="tooltip"
                      title="ion-close-round"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-close"
                      data-bs-toggle="tooltip"
                      title="ion-close"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-close-circled"
                      data-bs-toggle="tooltip"
                      title="ion-close-circled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-plus-round"
                      data-bs-toggle="tooltip"
                      title="ion-plus-round"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-plus"
                      data-bs-toggle="tooltip"
                      title="ion-plus"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-plus-circled"
                      data-bs-toggle="tooltip"
                      title="ion-plus-circled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-minus-round"
                      data-bs-toggle="tooltip"
                      title="ion-minus-round"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-minus"
                      data-bs-toggle="tooltip"
                      title="ion-minus"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-minus-circled"
                      data-bs-toggle="tooltip"
                      title="ion-minus-circled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-information"
                      data-bs-toggle="tooltip"
                      title="ion-information"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-information-circled"
                      data-bs-toggle="tooltip"
                      title="ion-information-circled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-help"
                      data-bs-toggle="tooltip"
                      title="ion-help"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-help-circled"
                      data-bs-toggle="tooltip"
                      title="ion-help-circled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-help-buoy"
                      data-bs-toggle="tooltip"
                      title="ion-help-buoy"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-asterisk"
                      data-bs-toggle="tooltip"
                      title="ion-asterisk"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-alert"
                      data-bs-toggle="tooltip"
                      title="ion-alert"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-alert-circled"
                      data-bs-toggle="tooltip"
                      title="ion-alert-circled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-refresh"
                      data-bs-toggle="tooltip"
                      title="ion-refresh"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-loop"
                      data-bs-toggle="tooltip"
                      title="ion-loop"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-shuffle"
                      data-bs-toggle="tooltip"
                      title="ion-shuffle"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-home"
                      data-bs-toggle="tooltip"
                      title="ion-home"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-search"
                      data-bs-toggle="tooltip"
                      title="ion-search"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-flag"
                      data-bs-toggle="tooltip"
                      title="ion-flag"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-star"
                      data-bs-toggle="tooltip"
                      title="ion-star"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-heart"
                      data-bs-toggle="tooltip"
                      title="ion-heart"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-heart-broken"
                      data-bs-toggle="tooltip"
                      title="ion-heart-broken"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-gear-a"
                      data-bs-toggle="tooltip"
                      title="ion-gear-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-gear-b"
                      data-bs-toggle="tooltip"
                      title="ion-gear-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-toggle-filled"
                      data-bs-toggle="tooltip"
                      title="ion-toggle-filled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-toggle"
                      data-bs-toggle="tooltip"
                      title="ion-toggle"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-settings"
                      data-bs-toggle="tooltip"
                      title="ion-settings"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-wrench"
                      data-bs-toggle="tooltip"
                      title="ion-wrench"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-folder"
                      data-bs-toggle="tooltip"
                      title="ion-folder"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-hammer"
                      data-bs-toggle="tooltip"
                      title="ion-hammer"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-edit"
                      data-bs-toggle="tooltip"
                      title="ion-edit"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-trash-a"
                      data-bs-toggle="tooltip"
                      title="ion-trash-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-trash-b"
                      data-bs-toggle="tooltip"
                      title="ion-trash-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-document"
                      data-bs-toggle="tooltip"
                      title="ion-document"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-document-text"
                      data-bs-toggle="tooltip"
                      title="ion-document-text"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-clipboard"
                      data-bs-toggle="tooltip"
                      title="ion-clipboard"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-scissors"
                      data-bs-toggle="tooltip"
                      title="ion-scissors"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-funnel"
                      data-bs-toggle="tooltip"
                      title="ion-funnel"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-bookmark"
                      data-bs-toggle="tooltip"
                      title="ion-bookmark"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-email"
                      data-bs-toggle="tooltip"
                      title="ion-email"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-folder"
                      data-bs-toggle="tooltip"
                      title="ion-folder"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-filing"
                      data-bs-toggle="tooltip"
                      title="ion-filing"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-archive"
                      data-bs-toggle="tooltip"
                      title="ion-archive"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-reply"
                      data-bs-toggle="tooltip"
                      title="ion-reply"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-reply-all"
                      data-bs-toggle="tooltip"
                      title="ion-reply-all"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-forward"
                      data-bs-toggle="tooltip"
                      title="ion-forward"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-share"
                      data-bs-toggle="tooltip"
                      title="ion-share"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-paper-airplane"
                      data-bs-toggle="tooltip"
                      title="ion-paper-airplane"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-link"
                      data-bs-toggle="tooltip"
                      title="ion-link"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-paperclip"
                      data-bs-toggle="tooltip"
                      title="ion-paperclip"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-compose"
                      data-bs-toggle="tooltip"
                      title="ion-compose"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-briefcase"
                      data-bs-toggle="tooltip"
                      title="ion-briefcase"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-medkit"
                      data-bs-toggle="tooltip"
                      title="ion-medkit"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-at"
                      data-bs-toggle="tooltip"
                      title="ion-at"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pound"
                      data-bs-toggle="tooltip"
                      title="ion-pound"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-quote"
                      data-bs-toggle="tooltip"
                      title="ion-quote"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-cloud"
                      data-bs-toggle="tooltip"
                      title="ion-cloud"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-upload"
                      data-bs-toggle="tooltip"
                      title="ion-upload"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-more"
                      data-bs-toggle="tooltip"
                      title="ion-more"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-grid"
                      data-bs-toggle="tooltip"
                      title="ion-grid"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-calendar"
                      data-bs-toggle="tooltip"
                      title="ion-calendar"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-clock"
                      data-bs-toggle="tooltip"
                      title="ion-clock"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-compass"
                      data-bs-toggle="tooltip"
                      title="ion-compass"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pinpoint"
                      data-bs-toggle="tooltip"
                      title="ion-pinpoint"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pin"
                      data-bs-toggle="tooltip"
                      title="ion-pin"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-navigate"
                      data-bs-toggle="tooltip"
                      title="ion-navigate"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-location"
                      data-bs-toggle="tooltip"
                      title="ion-location"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-map"
                      data-bs-toggle="tooltip"
                      title="ion-map"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-model-s"
                      data-bs-toggle="tooltip"
                      title="ion-model-s"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-locked"
                      data-bs-toggle="tooltip"
                      title="ion-locked"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-unlocked"
                      data-bs-toggle="tooltip"
                      title="ion-unlocked"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-key"
                      data-bs-toggle="tooltip"
                      title="ion-key"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-graph-up-right"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-graph-up-right"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-graph-down-right"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-graph-down-right"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-arrow-graph-down-left"
                      data-bs-toggle="tooltip"
                      title="ion-arrow-graph-down-left"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-stats-bars"
                      data-bs-toggle="tooltip"
                      title="ion-stats-bars"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-connection-bars"
                      data-bs-toggle="tooltip"
                      title="ion-connection-bars"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pie-graph"
                      data-bs-toggle="tooltip"
                      title="ion-pie-graph"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chatbubble"
                      data-bs-toggle="tooltip"
                      title="ion-chatbubble"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chatbubble-working"
                      data-bs-toggle="tooltip"
                      title="ion-chatbubble-working"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chatbubbles"
                      data-bs-toggle="tooltip"
                      title="ion-chatbubbles"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chatbox"
                      data-bs-toggle="tooltip"
                      title="ion-chatbox"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chatbox-working"
                      data-bs-toggle="tooltip"
                      title="ion-chatbox-working"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-chatboxes"
                      data-bs-toggle="tooltip"
                      title="ion-chatboxes"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-person"
                      data-bs-toggle="tooltip"
                      title="ion-person"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-person-add"
                      data-bs-toggle="tooltip"
                      title="ion-person-add"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-person-stalker"
                      data-bs-toggle="tooltip"
                      title="ion-person-stalker"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-woman"
                      data-bs-toggle="tooltip"
                      title="ion-woman"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-man"
                      data-bs-toggle="tooltip"
                      title="ion-man"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-female"
                      data-bs-toggle="tooltip"
                      title="ion-female"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-male"
                      data-bs-toggle="tooltip"
                      title="ion-male"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-fork"
                      data-bs-toggle="tooltip"
                      title="ion-fork"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-knife"
                      data-bs-toggle="tooltip"
                      title="ion-knife"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-spoon"
                      data-bs-toggle="tooltip"
                      title="ion-spoon"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-beer"
                      data-bs-toggle="tooltip"
                      title="ion-beer"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-wineglass"
                      data-bs-toggle="tooltip"
                      title="ion-wineglass"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-coffee"
                      data-bs-toggle="tooltip"
                      title="ion-coffee"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-icecream"
                      data-bs-toggle="tooltip"
                      title="ion-icecream"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pizza"
                      data-bs-toggle="tooltip"
                      title="ion-pizza"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-power"
                      data-bs-toggle="tooltip"
                      title="ion-power"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-mouse"
                      data-bs-toggle="tooltip"
                      title="ion-mouse"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-battery-full"
                      data-bs-toggle="tooltip"
                      title="ion-battery-full"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-battery-half"
                      data-bs-toggle="tooltip"
                      title="ion-battery-half"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-battery-low"
                      data-bs-toggle="tooltip"
                      title="ion-battery-low"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-battery-empty"
                      data-bs-toggle="tooltip"
                      title="ion-battery-empty"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-battery-charging"
                      data-bs-toggle="tooltip"
                      title="ion-battery-charging"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-bluetooth"
                      data-bs-toggle="tooltip"
                      title="ion-bluetooth"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-calculator"
                      data-bs-toggle="tooltip"
                      title="ion-calculator"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-camera"
                      data-bs-toggle="tooltip"
                      title="ion-camera"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-eye"
                      data-bs-toggle="tooltip"
                      title="ion-eye"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-eye-disabled"
                      data-bs-toggle="tooltip"
                      title="ion-eye-disabled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-flash"
                      data-bs-toggle="tooltip"
                      title="ion-flash"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-flash-off"
                      data-bs-toggle="tooltip"
                      title="ion-flash-off"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-qr-scanner"
                      data-bs-toggle="tooltip"
                      title="ion-qr-scanner"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-image"
                      data-bs-toggle="tooltip"
                      title="ion-image"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-images"
                      data-bs-toggle="tooltip"
                      title="ion-images"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-contrast"
                      data-bs-toggle="tooltip"
                      title="ion-contrast"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-wand"
                      data-bs-toggle="tooltip"
                      title="ion-wand"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-aperture"
                      data-bs-toggle="tooltip"
                      title="ion-aperture"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-monitor"
                      data-bs-toggle="tooltip"
                      title="ion-monitor"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-laptop"
                      data-bs-toggle="tooltip"
                      title="ion-laptop"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ipad"
                      data-bs-toggle="tooltip"
                      title="ion-ipad"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-iphone"
                      data-bs-toggle="tooltip"
                      title="ion-iphone"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ipod"
                      data-bs-toggle="tooltip"
                      title="ion-ipod"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-printer"
                      data-bs-toggle="tooltip"
                      title="ion-printer"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-usb"
                      data-bs-toggle="tooltip"
                      title="ion-usb"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-outlet"
                      data-bs-toggle="tooltip"
                      title="ion-outlet"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-bug"
                      data-bs-toggle="tooltip"
                      title="ion-bug"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-code"
                      data-bs-toggle="tooltip"
                      title="ion-code"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-code-working"
                      data-bs-toggle="tooltip"
                      title="ion-code-working"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-code-download"
                      data-bs-toggle="tooltip"
                      title="ion-code-download"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-fork-repo"
                      data-bs-toggle="tooltip"
                      title="ion-fork-repo"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-network"
                      data-bs-toggle="tooltip"
                      title="ion-network"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pull-request"
                      data-bs-toggle="tooltip"
                      title="ion-pull-request"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-merge"
                      data-bs-toggle="tooltip"
                      title="ion-merge"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-game-controller-a"
                      data-bs-toggle="tooltip"
                      title="ion-game-controller-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-game-controller-b"
                      data-bs-toggle="tooltip"
                      title="ion-game-controller-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-xbox"
                      data-bs-toggle="tooltip"
                      title="ion-xbox"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-playstation"
                      data-bs-toggle="tooltip"
                      title="ion-playstation"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-steam"
                      data-bs-toggle="tooltip"
                      title="ion-steam"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-closed-captioning"
                      data-bs-toggle="tooltip"
                      title="ion-closed-captioning"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-videocamera"
                      data-bs-toggle="tooltip"
                      title="ion-videocamera"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-film-marker"
                      data-bs-toggle="tooltip"
                      title="ion-film-marker"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-disc"
                      data-bs-toggle="tooltip"
                      title="ion-disc"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-headphone"
                      data-bs-toggle="tooltip"
                      title="ion-headphone"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-music-note"
                      data-bs-toggle="tooltip"
                      title="ion-music-note"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-radio-waves"
                      data-bs-toggle="tooltip"
                      title="ion-radio-waves"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-speakerphone"
                      data-bs-toggle="tooltip"
                      title="ion-speakerphone"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-mic-a"
                      data-bs-toggle="tooltip"
                      title="ion-mic-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-mic-b"
                      data-bs-toggle="tooltip"
                      title="ion-mic-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-mic-c"
                      data-bs-toggle="tooltip"
                      title="ion-mic-c"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-volume-high"
                      data-bs-toggle="tooltip"
                      title="ion-volume-high"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-volume-medium"
                      data-bs-toggle="tooltip"
                      title="ion-volume-medium"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-volume-low"
                      data-bs-toggle="tooltip"
                      title="ion-volume-low"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-volume-mute"
                      data-bs-toggle="tooltip"
                      title="ion-volume-mute"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-levels"
                      data-bs-toggle="tooltip"
                      title="ion-levels"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-play"
                      data-bs-toggle="tooltip"
                      title="ion-play"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pause"
                      data-bs-toggle="tooltip"
                      title="ion-pause"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-stop"
                      data-bs-toggle="tooltip"
                      title="ion-stop"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-record"
                      data-bs-toggle="tooltip"
                      title="ion-record"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-skip-forward"
                      data-bs-toggle="tooltip"
                      title="ion-skip-forward"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-skip-backward"
                      data-bs-toggle="tooltip"
                      title="ion-skip-backward"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-eject"
                      data-bs-toggle="tooltip"
                      title="ion-eject"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-bag"
                      data-bs-toggle="tooltip"
                      title="ion-bag"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-card"
                      data-bs-toggle="tooltip"
                      title="ion-card"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-cash"
                      data-bs-toggle="tooltip"
                      title="ion-cash"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pricetag"
                      data-bs-toggle="tooltip"
                      title="ion-pricetag"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-pricetags"
                      data-bs-toggle="tooltip"
                      title="ion-pricetags"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-thumbsup"
                      data-bs-toggle="tooltip"
                      title="ion-thumbsup"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-thumbsdown"
                      data-bs-toggle="tooltip"
                      title="ion-thumbsdown"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-happy"
                      data-bs-toggle="tooltip"
                      title="ion-happy"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-sad"
                      data-bs-toggle="tooltip"
                      title="ion-sad"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-trophy"
                      data-bs-toggle="tooltip"
                      title="ion-trophy"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-podium"
                      data-bs-toggle="tooltip"
                      title="ion-podium"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ribbon-a"
                      data-bs-toggle="tooltip"
                      title="ion-ribbon-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ribbon-b"
                      data-bs-toggle="tooltip"
                      title="ion-ribbon-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-university"
                      data-bs-toggle="tooltip"
                      title="ion-university"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-magnet"
                      data-bs-toggle="tooltip"
                      title="ion-magnet"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-beaker"
                      data-bs-toggle="tooltip"
                      title="ion-beaker"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-flask"
                      data-bs-toggle="tooltip"
                      title="ion-flask"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-egg"
                      data-bs-toggle="tooltip"
                      title="ion-egg"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-earth"
                      data-bs-toggle="tooltip"
                      title="ion-earth"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-planet"
                      data-bs-toggle="tooltip"
                      title="ion-planet"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-lightbulb"
                      data-bs-toggle="tooltip"
                      title="ion-lightbulb"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-cube"
                      data-bs-toggle="tooltip"
                      title="ion-cube"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-leaf"
                      data-bs-toggle="tooltip"
                      title="ion-leaf"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-waterdrop"
                      data-bs-toggle="tooltip"
                      title="ion-waterdrop"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-flame"
                      data-bs-toggle="tooltip"
                      title="ion-flame"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-fireball"
                      data-bs-toggle="tooltip"
                      title="ion-fireball"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-bonfire"
                      data-bs-toggle="tooltip"
                      title="ion-bonfire"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-umbrella"
                      data-bs-toggle="tooltip"
                      title="ion-umbrella"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-nuclear"
                      data-bs-toggle="tooltip"
                      title="ion-nuclear"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-no-smoking"
                      data-bs-toggle="tooltip"
                      title="ion-no-smoking"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-thermometer"
                      data-bs-toggle="tooltip"
                      title="ion-thermometer"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-speedometer"
                      data-bs-toggle="tooltip"
                      title="ion-speedometer"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-plane"
                      data-bs-toggle="tooltip"
                      title="ion-plane"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-jet"
                      data-bs-toggle="tooltip"
                      title="ion-jet"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-load-a"
                      data-bs-toggle="tooltip"
                      title="ion-load-a"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-load-b"
                      data-bs-toggle="tooltip"
                      title="ion-load-b"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-load-c"
                      data-bs-toggle="tooltip"
                      title="ion-load-c"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-load-d"
                      data-bs-toggle="tooltip"
                      title="ion-load-d"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-ionic-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-ionic-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-back"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-back"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-forward"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-forward"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-up"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-up"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-right"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-right"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-down"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-down"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-left"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-left"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-thin-up"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-thin-up"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-thin-right"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-thin-right"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-thin-down"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-thin-down"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-arrow-thin-left"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-arrow-thin-left"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-circle-filled"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-circle-filled"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-circle-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-circle-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-checkmark-empty"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-checkmark-empty"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-checkmark-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-checkmark-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-checkmark"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-checkmark"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-plus-empty"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-plus-empty"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-plus-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-plus-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-plus"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-plus"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-close-empty"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-close-empty"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-close-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-close-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-close"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-close"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-minus-empty"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-minus-empty"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-minus-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-minus-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-minus"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-minus"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-information-empty"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-information-empty"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-information-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-information-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-information"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-information"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-help-empty"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-help-empty"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-help-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-help-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-help"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-help"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-search"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-search"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-search-strong"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-search-strong"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-star"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-star"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-star-half"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-star-half"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-star-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-star-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-heart"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-heart"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-heart-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-heart-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-more"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-more"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-more-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-more-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-home"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-home"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-home-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-home-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-cloud"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-cloud"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-cloud-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-cloud-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-cloud-upload"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-cloud-upload"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-cloud-upload-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-cloud-upload-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-cloud-download"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-cloud-download"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-cloud-download-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-cloud-download-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-upload"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-upload"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-upload-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-upload-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-download"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-download"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-refresh"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-refresh"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-refresh-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-refresh-outline"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-refresh-empty"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-refresh-empty"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-reload"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-reload"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-loop-strong"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-loop-strong"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-loop"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-loop"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-bookmarks"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-bookmarks"
                    />
                  </li>
                  <li>
                    <i
                      className="ion-ios7-bookmarks-outline"
                      data-bs-toggle="tooltip"
                      title="ion-ios7-bookmarks-outline"
                    />
                  </li>
                </ul>
              </div>
            </div>
            {/* end card-body */}
          </div>
          {/* end card */}
        </div>
        {/* end col */}
      </div>
      {/* end row */}
    </div>
    {/* End Content */}
    {/* Start Footer */}
    <div className="footer d-sm-flex align-items-center justify-content-between bg-white py-2 px-4 border-top">
      <p className="text-dark mb-0">
        ©
        <Link to="#" className="link-primary">
          Kanakku
        </Link>
        , All Rights Reserved
      </p>
      <p className="text-dark">Version : 1.3.8</p>
    </div>
    {/* End Footer */}
  </div>
  {/* ========================
			End Page Content
		========================= */}
</>

  )
}

export default IconIonic
