export const AppointmentsData = [
  {
    id: "1",
    Date_Time: "30 Apr 2026- 09:30 AM",
    Patient: "Alberto Ripley",
    Phone: "+1 56556 54565",
    Patient_Image: "user-01.jpg",
    Doctor_Image: "doctor-01.jpg",
    Doctor: "Dr. Mick Thompson",
    role: "Cardiologist",
    Mode: "In-person",
    Status: "Checked Out",
  },
  {
    id: "2",
    Date_Time: "15 Apr 2026- 11:20 AM",
    Patient: "Susan Babin",
    Phone: "+1 65658 95654",
    Patient_Image: "user-02.jpg",
    Doctor_Image: "doctor-02.jpg",
    Doctor: "Dr. Sarah Johnson",
    role: "Orthopedic Surgeon",
    Mode: "Online",
    Status: "Checked In",
  },
  {
    id: "3",
    Date_Time: "02 Apr 2026- 08:15 AM",
    Patient: "Carol Lam",
    Phone: "+1 55654 56647",
    Patient_Image: "user-03.jpg",
    Doctor_Image: "doctor-03.jpg",
    Doctor: "Dr. Emily Carter",
    role: "Pediatrician",
    Mode: "In-Person",
    Status: "Cancelled",
  },
  {
    id: "4",
    Date_Time: "27 Mar 2026- 02:00 PM",
    Patient: "Marsha Noland",
    Phone: "+1 65668 54558",
    Patient_Image: "user-04.jpg",
    Doctor_Image: "doctor-04.jpg",
    Doctor: "Dr. David Lee",
    role: "Gynecologist",
    Mode: "30 Apr 2025",
    Status: "Schedule",
  },
  {
    id: "5",
    Date_Time: "12 Mar 2026- 05:40 PM",
    Patient: "Irma Armstrong",
    Phone: "+1 45214 66568",
    Patient_Image: "user-05.jpg",
    Doctor_Image: "doctor-05.jpg",
    Doctor: "Dr. Anna Kim",
    role: "Psychiatrist",
    Mode: "Online",
    Status: "Confirmed",
  },
  {
    id: "6",
    Date_Time: "24 Feb 2026- 09:20 AM",
    Patient: "Ezra Belcher",
    Phone: "+1 65895 41247",
    Patient_Image: "user-06.jpg",
    Doctor_Image: "doctor-06.jpg",
    Doctor: "Dr. John Smith",
    role: "Neurosurgeon",
    Mode: "In-Person",
    Status: "Cancelled",
  },
  {
    id: "7",
    Date_Time: "16 Feb 2026- 11:40 AM",
    Patient: "Glen Lentz",
    Phone: "+1 62458 45845",
    Patient_Image: "user-07.jpg",
    Doctor_Image: "doctor-07.jpg",
    Doctor: "Dr. Lisa White",
    role: "Oncologist",
    Mode: "Online",
    Status: "Confirmed",
  },
  {
    id: "8",
    Date_Time: "01 Feb 2026- 04:00 PM",
    Patient: "Bernard Griffith",
    Phone: "+1 61422 45214",
    Patient_Image: "user-08.jpg",
    Doctor_Image: "doctor-08.jpg",
    Doctor: "Dr. Patricia Brown",
    role: "Pulmonologist",
    Mode: "Online",
    Status: "Checked Out",
  },
  {
    id: "9",
    Date_Time: "25 Jan 2026- 03:10 PM",
    Patient: "John Elsass",
    Phone: "+1 47851 26371",
    Patient_Image: "user-09.jpg",
    Doctor_Image: "doctor-09.jpg",
    Doctor: "Dr. Rachel Green",
    role: "Urologist",
    Mode: "Online",
    Status: "Schedule",
  },
  {
    id: "10",
    Date_Time: "12 Jan 2026- 03:10 PM",
    Patient: "John Albert",
    Phone: "+1 47851 35267",
    Patient_Image: "user-10.jpg",
    Doctor_Image: "doctor-10.jpg",
    Doctor: "Dr. Michael Smith",
    role: "Cardiologist",
    Mode: "In-Person",
    Status: "cancelled",
  },
];
