export const AppointmentReportData = [
  {
    id: "1",
    Patient: "Alberto Ripley",
    DateTime: "May 27 2026- 09:30 AM",
    InvoiceID: "#INV0020",
    Practioner: "Dr. Mick Thompson",
    Location: "California",
    Status: "Checked Out",
  },
  {
    id: "2",
    Patient: "Susan Babin",
    DateTime: "May 27 2026- 10:00 AM",
    InvoiceID: "#INV0019",
    Practioner: "Dr. Sarah Johnson",
    Location: "Texas",
    Status: "Checked in",
  },
  {
    id: "3",
    Patient: "Carol Lam",
    DateTime: "May 28 2026- 10:00 AM",
    InvoiceID: "#INV0018",
    Practioner: "Dr. Emily Carter",
    Location: "New York",
    Status: "Cancelled",
  },
  {
    id: "4",
    Patient: "Marsha Noland",
    DateTime: "May 28 2026- 10:30 AM",
    InvoiceID: "#INV0017",
    Practioner: "Dr. David Lee",
    Location: "Florida",
    Status: "Schedule",
  },
  {
    id: "5",
    Patient: "Irma Armstrong",
    DateTime: "May 28 2026- 11: 15 AM",
    InvoiceID: "#INV0016",
    Practioner: "Dr. Anna Kim",
    Location: "Illinois",
    Status: "Confirmed",
  },
  {
    id: "6",
    Patient: "Jesus Adams",
    DateTime: "May 29 2026- 11:30 AM",
    InvoiceID: "#INV0015",
    Practioner: "Dr. John Smith",
    Location: "Pennsylvania",
    Status: "Confirmed",
  },
  {
    id: "7",
    Patient: "Ezra Belcher",
    DateTime: "May 30 2026- 09:30 AM",
    InvoiceID: "#INV0014",
    Practioner: "Dr. Lisa White",
    Location: "Ohio",
    Status: "Cancelled",
  },
  {
    id: "8",
    Patient: "Glen Lentz",
    DateTime: "May 30 2026- 10:00 AM",
    InvoiceID: "#INV0013",
    Practioner: "Dr. Patricia Brown",
    Location: "Georgia",
    Status: "Confirmed",
  },
  {
    id: "9",
    Patient: "Bernard Griffith",
    DateTime: "May 30 2026- 11:00 AM",
    InvoiceID: "#INV0012",
    Practioner: "Dr. Rachel Green",
    Location: "North Carolina",
    Status: "Checked Out",
  },
  {
    id: "10",
    Patient: "John Elsass",
    DateTime: "May 30 2026- 11:00 AM",
    InvoiceID: "#INV0011",
    Practioner: "Dr. Michael Smith",
    Location: "Michigan",
    Status: "Schedule",
  },
];
