export const AssertsListData = [
  {
    id: "1",
    AssetID: "#AST001",
    AssetUser: "James Adair",
    Image: "user-01.jpg",
    Assets: "VitalScan Monitor",
    PurchaseDate: "30 Mar 2025",
    Warrenty: "3 Years",
    WarrantyEnd: "30 Mar 2028",
    Amount: "$2587",
    Status: "Approved",
  },
  {
    id: "2",
    AssetID: "#AST002",
    AssetUser: "Adam Milne",
    Image: "user-02.jpg",
    Assets: "MediScope",
    PurchaseDate: "28 Mar 2025",
    Warrenty: "10 Years",
    WarrantyEnd: "28 Mar 2028",
    Amount: "$47810",
    Status: "Approved",
  },
  {
    id: "3",
    AssetID: "#AST003",
    AssetUser: "Richard Clark",
    Image: "user-03.jpg",
    Assets: "ThermoTrack",
    PurchaseDate: "20 Mar 2025",
    Warrenty: "1 Years",
    WarrantyEnd: "20 Mar 2028",
    Amount: "$54789",
    Status: "Pending",
  },
  {
    id: "4",
    AssetID: "#AST004",
    AssetUser: "Robert Reid",
    Image: "user-04.jpg",
    Assets: "InjecSure",
    PurchaseDate: "15 Mar 2025",
    Warrenty: "3 Years",
    WarrantyEnd: "15 Mar 2029",
    Amount: "$21770",
    Status: "Pending",
  },
  {
    id: "5",
    AssetID: "#AST005",
    AssetUser: "Dottie Jeny",
    Image: "user-05.jpg",
    Assets: "LabMate",
    PurchaseDate: "07 Mar 2025",
    Warrenty: "5 Years",
    WarrantyEnd: "07 Mar 2028",
    Amount: "$32580",
    Status: "Approved",
  },
  {
    id: "6",
    AssetID: "#AST006",
    AssetUser: "Cheryl Bilodeau",
    Image: "user-06.jpg",
    Assets: "MicroView",
    PurchaseDate: "27 Feb 2025",
    Warrenty: "Up to 5Years",
    WarrantyEnd: "27 Feb 2028",
    Amount: "$32547",
    Status: "Approved",
  },
  {
    id: "7",
    AssetID: "#AST007",
    AssetUser: "Valerie Padgett",
    Image: "user-07.jpg",
    Assets: "First Aid Hub",
    PurchaseDate: "20 Feb 2025",
    Warrenty: "2 Years",
    WarrantyEnd: "20 Feb 2027",
    Amount: "$54100",
    Status: "Returned",
  },
  {
    id: "8",
    AssetID: "#AST008",
    AssetUser: "Diane Nash",
    Image: "user-08.jpg",
    Assets: "MediCart",
    PurchaseDate: "12 Feb 2025",
    Warrenty: "10 Years",
    WarrantyEnd: "12 Feb 2035",
    Amount: "$246798",
    Status: "Approved",
  },
  {
    id: "9",
    AssetID: "#AST009",
    AssetUser: "Sally Cavazos",
    Image: "user-09.jpg",
    Assets: "SterilBox",
    PurchaseDate: "21 Jan 2025",
    Warrenty: "5 Years",
    WarrantyEnd: "21 Jan 2028",
    Amount: "$12011",
    Status: "Approved",
  },
  {
    id: "10",
    AssetID: "#AST0010",
    AssetUser: "Forest Heath",
    Image: "user-10.jpg",
    Assets: "MediLogix",
    PurchaseDate: "15 Jan 2025",
    Warrenty: "2 Years",
    WarrantyEnd: "15 Jan 2028",
    Amount: "$35421",
    Status: "Pending",
  },
];
