export const CitiesData = [
  {
    id: "1",
    Country_Code: "US",
    img: "us.svg",
    Country: "USA",
    State: "California",
    City: "Los Angeles",
    Status: "Active",
  },
  {
    id: "1",
    Country_Code: "CA",
    img: "ca.svg",
    Country: "Canada",
    State: "Ontario",
    City: "Toronto",
    Status: "Active",
  },
  {
    id: "1",
    Country_Code: "UK",
    img: "uk.svg",
    Country: "UK",
    State: "England",
    City: "London",
    Status: "Active",
  },
  {
    id: "1",
    Country_Code: "DE",
    img: "de.svg",
    Country: "Germany",
    State: "Bavaria",
    City: "Munich",
    Status: "Active",
  },
  {
    id: "1",
    Country_Code: "FR",
    img: "fr.svg",
    Country: "France",
    State: "Le-de-France",
    City: "Paris",
    Status: "Active",
  },
  {
    id: "1",
    Country_Code: "AR",
    img: "ar.svg",
    Country: "Argentina",
    State: "Buenos Aires",
    City: "Buenos Aires",
    Status: "Active",
  },
  {
    id: "1",
    Country_Code: "IN",
    img: "in.svg",
    Country: "India",
    State: "Tamil Nadu",
    City: "Mumbai",
    Status: "Active",
  },
  {
    id: "1",
    Country_Code: "IT",
    img: "it.svg",
    Country: "Italy",
    State: "Lombardy",
    City: "Milan",
    Status: "Active",
  },
  {
    id: "1",
    Country_Code: "NZ",
    img: "nz.svg",
    Country: "New Zealand",
    State: "Wellington",
    City: "Wellington",
    Status: "Inactive",
  },
  {
    id: "1",
    Country_Code: "AU",
    img: "au.svg",
    Country: "Australia",
    State: "New South Wales",
    City: "Sydney",
    Status: "Inactive",
  },
];
