export const CountriesData = [
  {
    id: "1",
    Country_Code: "US",
    Country: "USA",
    img: "us.svg",
    Status: "Active",
  },
  {
    id: "2",
    Country_Code: "CA",
    Country: "Canada",
    img: "ca.svg",
    Status: "Active",
  },
  {
    id: "3",
    Country_Code: "UK",
    Country: "UK",
    img: "uk.svg",
    Status: "Active",
  },
  {
    id: "4",
    Country_Code: "DE",
    Country: "Germany",
    img: "de.svg",
    Status: "Active",
  },
  {
    id: "5",
    Country_Code: "FR",
    Country: "France",
    img: "fr.svg",
    Status: "Active",
  },
  {
    id: "6",
    Country_Code: "AR",
    Country: "Argentina",
    img: "ar.svg",
    Status: "Active",
  },
  {
    id: "7",
    Country_Code: "IN",
    Country: "India",
    img: "in.svg",
    Status: "Active",
  },
  {
    id: "8",
    Country_Code: "IT",
    Country: "Italy",
    img: "it.svg",
    Status: "Active",
  },
  {
    id: "9",
    Country_Code: "NZ",
    Country: "New Zealand",
    img: "us.svg",
    Status: "Inactive",
  },
  {
    id: "10",
    Country_Code: "AU",
    Country: "Australia",
    img: "nz.svg",
    Status: "Inactive",
  },
];
