export const DataTablesData = [
  {
    key: "1",
    Name: "Tiger Nixon",
    Position: "System Architect",
    Office: "Edinburgh",
    Age: "61",
    Start_date: "2011 Apr 25",
    Salary: "$320,800",
  },
  {
    key: "2",
    Name: "Garrett Winters",
    Position: "Accountant",
    Office: "Tokyo",
    Age: "63",
    Start_date: "2011 Jul 25",
    Salary: "$170,750",
  },
  {
    key: "3",
    Name: "Ashton Cox",
    Position: "Junior Technical Author",
    Office: "San Francisco",
    Age: "66",
    Start_date: "2009 Jan 12",
    Salary: "$86,000",
  },
  {
    key: "4",
    Name: "Cedric Kelly",
    Position: "Senior Javascript Developer",
    Office: "Edinburgh",
    Age: "22",
    Start_date: "2012 Mar 29",
    Salary: "$433,060",
  },
  {
    key: "5",
    Name: "Airi Satou",
    Position: "Accountant",
    Office: "Tokyo",
    Age: "33",
    Start_date: "2008 Nov 28",
    Salary: "$162,700",
  },
  {
    key: "6",
    Name: "Brielle Williamson",
    Position: "Integration Specialist",
    Office: "New York",
    Age: "61",
    Start_date: "2012 Dec 02",
    Salary: "$372,000",
  },
  {
    key: "7",
    Name: "Herrod Chandler",
    Position: "Sales Assistant",
    Office: "San Francisco",
    Age: "59",
    Start_date: "2012 Aug 06",
    Salary: "$137,500",
  },
  {
    key: "8",
    Name: "Rhona Davidson",
    Position: "Integration Specialist",
    Office: "Tokyo",
    Age: "55",
    Start_date: "2010 Oct 14",
    Salary: "$327,900",
  },
  {
    key: "9",
    Name: "Colleen Hurst",
    Position: "Javascript Developer",
    Office: "San Francisco",
    Age: "39",
    Start_date: "2009 Sep 15",
    Salary: "$205,500",
  },
  {
    key: "10",
    Name: "Sonya Frost",
    Position: "Software Engineer",
    Office: "Edinburgh",
    Age: "23",
    Start_date: "2008 Dec 13",
    Salary: "$103,600",
  },
  {
    key: "11",
    Name: "Jena Gaines",
    Position: "Office Manager",
    Office: "London",
    Age: "30",
    Start_date: "2008 Dec 19",
    Salary: "$90,560",
  },
  {
    key: "12",
    Name: "Quinn Flynn",
    Position: "Support Lead",
    Office: "Edinburgh",
    Age: "22",
    Start_date: "2013 Mar 03",
    Salary: "$342,000",
  },
  {
    key: "12",
    Name: "Charde Marshall",
    Position: "Regional Director",
    Office: "San Francisco",
    Age: "36",
    Start_date: "2008 Oct 16",
    Salary: "$470,600",
  },
  {
    key: "14",
    Name: "Haley Kennedy",
    Position: "Senior Marketing Designer",
    Office: "London",
    Age: "43",
    Start_date: "2012 Dec 18",
    Salary: "$313,500",
  },
  {
    key: "15",
    Name: "Tatyana Fitzpatrick",
    Position: "Regional Director",
    Office: "London",
    Age: "19",
    Start_date: "2010 Mar 17",
    Salary: "$385,750",
  },
  {
    key: "16",
    Name: "Michael Silva",
    Position: "Marketing Designer",
    Office: "London",
    Age: "66",
    Start_date: "2012 Nov 27",
    Salary: "$198,500",
  },
  {
    key: "17",
    Name: "Paul Byrd",
    Position: "Chief Financial Officer (CFO)",
    Office: "New York",
    Age: "64",
    Start_date: "2010 Jun 09",
    Salary: "$725,000",
  },
  {
    key: "18",
    Name: "Gloria Little",
    Position: "Systems Administrator",
    Office: "New York",
    Age: "59",
    Start_date: "2009 Apr 10",
    Salary: "$237,500",
  },
  {
    key: "19",
    Name: "Bradley Greer",
    Position: "Software Engineer",
    Office: "London",
    Age: "41",
    Start_date: "2012 Oct 13",
    Salary: "$132,000",
  },
  {
    key: "20",
    Name: "Dai Rios",
    Position: "Personnel Lead",
    Office: "Edinburgh",
    Age: "35",
    Start_date: "2012 Sep 26",
    Salary: "$217,500",
  },
  {
    key: "21",
    Name: "Jenette Caldwell",
    Position: "Development Lead",
    Office: "New York",
    Age: "30",
    Start_date: "2011 Sep 03",
    Salary: "$345,000",
  },
  {
    key: "22",
    Name: "Yuri Berry",
    Position: "Chief Marketing Officer (CMO)",
    Office: "New York",
    Age: "40",
    Start_date: "2009 Jun 25",
    Salary: "$675,000",
  },
  {
    key: "23",
    Name: "Caesar Vance",
    Position: "Pre-Sales Support",
    Office: "New York",
    Age: "21",
    Start_date: "2011 Dec 12",
    Salary: "$106,450",
  },
  {
    key: "24",
    Name: "Doris Wilder",
    Position: "Sales Assistant",
    Office: "Sidney",
    Age: "23",
    Start_date: "2010 Sep 20",
    Salary: "$85,600",
  },
  {
    key: "25",
    Name: "Angelica Ramos",
    Position: "Chief Executive Officer (CEO)",
    Office: "London",
    Age: "47",
    Start_date: "2009 Oct 09",
    Salary: "$1,200,000",
  },
  {
    key: "26",
    Name: "Gavin Joyce",
    Position: "Developer",
    Office: "Edinburgh",
    Age: "42",
    Start_date: "2010 Dec 22",
    Salary: "$92,575",
  },
  {
    key: "27",
    Name: "Jennifer Chang",
    Position: "Regional Director",
    Office: "Singapore",
    Age: "28",
    Start_date: "2010 Nov 14",
    Salary: "$357,650",
  },
  {
    key: "28",
    Name: "Brenden Wagner",
    Position: "Software Engineer",
    Office: "San Francisco",
    Age: "28",
    Start_date: "2011 Jun 07",
    Salary: "$206,850",
  },
  {
    key: "29",
    Name: "Fiona Green",
    Position: "Chief Operating Officer (COO)",
    Office: "San Francisco",
    Age: "48",
    Start_date: "2010 Mar 11",
    Salary: "$850,000",
  },
  {
    key: "30",
    Name: "Shou Itou",
    Position: "Regional Marketing",
    Office: "Tokyo",
    Age: "20",
    Start_date: "2011 Aug 14",
    Salary: "$163,000",
  },
];
