export const DeleteRequestData = [
  {
    id: "1",
    User: "James Adair",
    img: "user-08.jpg",
    Requisition_Date: "22 Apr 2025",
    Delete_Request_Date: "30 Apr 2025",
    Status: "Available",
  },
  {
    id: "2",
    User: "Adam Milne",
    img: "user-03.jpg",
    Requisition_Date: "12 Apr 2025",
    Delete_Request_Date: "15 Apr 2025",
    Status: "Available",
  },
  {
    id: "3",
    User: "Richard Clark",
    img: "user-04.jpg",
    Requisition_Date: "01 Apr 2025",
    Delete_Request_Date: "02 Apr 2025",
    Status: "Unavailable",
  },
  {
    id: "4",
    User: "Robert Reid",
    img: "user-05.jpg",
    Requisition_Date: "05 Mar 2025",
    Delete_Request_Date: "12 Mar 2025",
    Status: "Available",
  },
  {
    id: "5",
    User: "Dottie Jeny",
    img: "user-06.jpg",
    Requisition_Date: "20 Mar 2025",
    Delete_Request_Date: "27 Mar 2025",
    Status: "Available",
  },
  {
    id: "6",
    User: "Cheryl Bilodeau",
    img: "user-07.jpg",
    Requisition_Date: "01 Mar 2025",
    Delete_Request_Date: "05 Mar 2025",
    Status: "Available",
  },
  {
    id: "7",
    User: "Valerie Padgett",
    img: "user-02.jpg",
    Requisition_Date: "15 Feb 2025",
    Delete_Request_Date: "24 Feb 2025",
    Status: "Available",
  },
  {
    id: "8",
    User: "Diane Nash",
    img: "user-25.jpg",
    Requisition_Date: "09 Feb 2025",
    Delete_Request_Date: "16 Feb 2025",
    Status: "Available",
  },
  {
    id: "9",
    User: "Sally Cavazos",
    img: "user-29.jpg",
    Requisition_Date: "01 Feb 2025",
    Delete_Request_Date: "01 Feb 2025",
    Status: "Available",
  },
  {
    id: "10",
    User: "Forest Heath",
    img: "user-12.jpg",
    Requisition_Date: "12 Jan 2025",
    Delete_Request_Date: "25 Jan 2025",
    Status: "Available",
  },
];
