export const DoctorPrescriptionsData = [
  {
    id: "1",
    Prescription_ID: "#PRE0025",
    Patient: "John Richard",
    img: "user-14.jpg",
    Prescribed_On: "19 Jan 2025",
  },
  {
    id: "2",
    Prescription_ID: "#PRE0024",
    Patient: "Susan Babin",
    img: "user-15.jpg",
    Prescribed_On: "12 Mar 2025",
  },
  {
    id: "3",
    Prescription_ID: "#PRE0023",
    Patient: "Marsha Noland",
    img: "user-16.jpg",
    Prescribed_On: "27 Mar 2025",
  },
  {
    id: "4",
    Prescription_ID: "#PRE0022",
    Patient: "Irma Armstrong",
    img: "user-17.jpg",
    Prescribed_On: "12 Mar 2025",
  },
  {
    id: "5",
    Prescription_ID: "#PRE0021",
    Patient: "Ezra Belcher",
    img: "user-18.jpg",
    Prescribed_On: "24 Feb 2025",
  },
  {
    id: "6",
    Prescription_ID: "#PRE0020",
    Patient: "Glen Lentz",
    img: "user-19.jpg",
    Prescribed_On: "16 Feb 2025",
  },
  {
    id: "7",
    Prescription_ID: "#PRE0019",
    Patient: "Bernard Griffith",
    img: "user-01.jpg",
    Prescribed_On: "30 Apr 2025",
  },
  {
    id: "8",
    Prescription_ID: "#PRE0018",
    Patient: "John Elsass",
    img: "user-21.jpg",
    Prescribed_On: "30 Apr 2025",
  },
  {
    id: "9",
    Prescription_ID: "#PRE0017",
    Patient: "Carol Lam",
    img: "user-22.jpg",
    Prescribed_On: "10 Jan 2025",
  },
  {
    id: "10",
    Prescription_ID: "#PRE0016",
    Patient: "Alberto Ripley",
    img: "user-23.jpg",
    Prescribed_On: "25 Jan 2025",
  },
];
