export const DoctorsListData = [
  {
    id: "1",
    Name_Designation: "Dr. Mick Thompson  ",
    img: "doctor-01.jpg",
    role: "Cardiologist",
    Department: "Cardiology",
    Phone: "+1 54554 54584",
    Email: "mick@example.com",
    Fees: "$458",
    Status: "Available",
  },
  {
    id: "2",
    Name_Designation: "Dr. Sarah Johnson  ",
    img: "doctor-02.jpg",
    role: "Orthopedic Surgeon",
    Department: "Orthopedics",
    Phone: "+1 43554 54584",
    Email: "sarah@example.com",
    Fees: "$512",
    Status: "Available",
  },
  {
    id: "3",
    Name_Designation: "Dr. Emily Carter  ",
    img: "doctor-03.jpg",
    role: "Pediatrician",
    Department: "Pediatrics",
    Phone: "+1 47554 54585",
    Email: "emily@example.com",
    Fees: "$635",
    Status: "Available",
  },
  {
    id: "4",
    Name_Designation: "Dr. David Lee ",
    img: "doctor-04.jpg",
    role: "Gynecologist",
    Department: "Gynecology",
    Phone: "+1 54114 54586",
    Email: "david@example.com",
    Fees: "$478",
    Status: "Available",
  },
  {
    id: "5",
    Name_Designation: "Dr. Anna Kim ",
    img: "doctor-05.jpg",
    role: "Psychiatrist",
    Department: "Psychiatry",
    Phone: "+1 51247 54587",
    Email: "anna@example.com",
    Fees: "$550",
    Status: "Available",
  },
  {
    id: "6",
    Name_Designation: "Dr. John Smith ",
    img: "doctor-06.jpg",
    role: "Neurosurgeon",
    Department: "Neurology",
    Phone: "+1 41452 54588",
    Email: "john@example.com",
    Fees: "$703",
    Status: "Unavailable",
  },
  {
    id: "7",
    Name_Designation: "Dr. Lisa White Oncologist",
    img: "doctor-07.jpg",
    role: "Oncologist",
    Department: "Oncologist",
    Phone: "+1 51425 54589",
    Email: "lisa@example.com",
    Fees: "$420",
    Status: "Available",
  },
  {
    id: "8",
    Name_Designation: "Dr. Patricia Brown ",
    img: "doctor-08.jpg",
    role: "Pulmonologist",
    Department: "Pulmonologist",
    Phone: "+1 42565 54590",
    Email: "patricia@example.com",
    Fees: "$590",
    Status: "Available",
  },
  {
    id: "9",
    Name_Designation: "Dr. Rachel Green",
    img: "doctor-09.jpg",
    Department: "Urologist",
    Phone: "+1 45214 54591",
    Email: "racheal@example.com",
    Fees: "$670",
    Status: "Available",
  },
  {
    id: "10",
    Name_Designation: "Dr. Michael Smith",
    img: "doctor-10.jpg",
    Department: "Cardiologist",
    Phone: "+1 41245 54592",
    Email: "micheal@example.com",
    Fees: "$530",
    Status: "Available",
  },
];
