export const ExpensesListData = [
  {
    id:"1",
    Expense: "Gloves & Masks",
    Category: "Medical Supplies",
    Amount: "$800",
    Date: "30 Apr 2025",
    Image: "user-01.jpg",
    PurchasedBy: "James Adair",
    PaymentMethod: "PayPal",
    Status: "Approved",
  },
  {
      id:"2",
    Expense: "Microscope Parts",
    Category: "Laboratory",
    Amount: "$930",
    Date: "15 Apr 2025",
    Image: "user-02.jpg",
    PurchasedBy: "Esther Schmidt",
    PaymentMethod: "Debit Card",
    Status: "Pending",
  },
  {
      id:"3",
    Expense: "Thermometers",
    Category: "Medical Supplies",
    Amount: "$850",
    Date: "02 Apr 2025",
    Image: "user-03.jpg",
    PurchasedBy: "Judi Lenahan",
    PaymentMethod: "Cheque",
    Status: "Approved",
  },
  {
      id:"4",
    Expense: "Disinfectant Supplies",
    Category: "Cleaning Services",
    Amount: "$700",
    Date: "27 Mar 2025",
    Image: "user-04.jpg",
    PurchasedBy: "Robert Reid",
    PaymentMethod: "Debit Card",
    Status: "Rejected",
  },
  {
      id:"5",
    Expense: "IV Sets",
    Category: "Medical Supplies",
    Amount: "$650",
    Date: "12 Mar 2025",
    Image: "user-12.jpg",
    PurchasedBy: "Dottie Sellers",
    PaymentMethod: "PayPal",
    Status: "New",
  },
  {
      id:"6",
    Expense: "Reagent Refill",
    Category: "Laboratory",
    Amount: "$430",
    Date: "05 Mar 2025",
    Image: "user-02.jpg",
    PurchasedBy: "Cheryl Bilodeau",
    PaymentMethod: "Cheque",
    Status: "Rejected",
  },
  {
      id:"7",
    Expense: "Syringes & Gauze",
    Category: "Medical Supplies",
    Amount: "$300",
    Date: "24 Feb 2025",
    Image: "user-07.jpg",
    PurchasedBy: "Valerie Padgett",
    PaymentMethod: "Debit Card",
    Status: "New",
  },
  {
      id:"8",
    Expense: "Blood Collection Tubes",
    Category: "Laboratory",
    Amount: "$450",
    Date: "16 Feb 2025",
    Image: "user-05.jpg",
    PurchasedBy: "Diane Nash",
    PaymentMethod: "Cheque",
    Status: "Approved",
  },
  {
      id:"9",
    Expense: "Bandages & Tapes",
    Category: "Medical Supplies",
    Amount: "$570",
    Date: "01 Feb 2025",
    Image: "user-07.jpg",
    PurchasedBy: "Sally Cavazos",
    PaymentMethod: "Debit Card",
    Status: "New",
  },
  {
      id:"10",
    Expense: "Tissue Slides",
    Category: "Laboratory",
    Amount: "$800",
    Date: "25 Jan 2025",
    Image: "user-09.jpg",
    PurchasedBy: "Forest Heath",
    PaymentMethod: "PayPal",
    Status: "Approved",
  },
];
