export const ExpenseReportData = [
  {
    id: "1",
    Expense: "Gloves & Masks",
    Category: "Medical Supplies",
    Amount: "$800",
    Date: "22 Apr 2025",
    PurchasedBy: "James Carter",
    Status: "Approved",
    PaymentMethod: "PayPal",
  },
  {
    id: "2",
    Expense: "Microscope Parts",
    Category: "Laboratory",
    Amount: "$930",
    Date: "12 Apr 2025",
    PurchasedBy: "Emily Johnson",
    Status: "Pending",
    PaymentMethod: "Debit Card",
  },
  {
    id: "3",
    Expense: "Thermometers",
    Category: "Medical Supplies",
    Amount: "$850",
    Date: "01 Apr 2025",
    PurchasedBy: "Robert Mitchell",
    Status: "Approved",
    PaymentMethod: "Cheque",
  },
  {
    id: "4",
    Expense: "Disinfectant Supplies",
    Category: "Cleaning Services",
    Amount: "$700",
    Date: "05 Mar 2025",
    PurchasedBy: "Sophia Miller",
    Status: "Rejected",
    PaymentMethod: "Cheque",
  },
  {
    id: "5",
    Expense: "IV Sets",
    Category: "Medical Supplies",
    Amount: "$650",
    Date: "20 Mar 2025",
    PurchasedBy: "Daniel Anderson",
    Status: "New",
    PaymentMethod: "PayPal",
  },
  {
    id: "6",
    Expense: "Reagent Refill",
    Category: "Laboratory",
    Amount: "$430",
    Date: "01 Mar 2025",
    PurchasedBy: "Olivia Davis",
    Status: "Rejected",
    PaymentMethod: "Debit Card",
  },
  {
    id: "7",
    Expense: "Syringes & Gauze",
    Category: "Medical Supplies",
    Amount: "$300",
    Date: "15 Feb 2025",
    PurchasedBy: "Michael Thompson",
    Status: "New",
    PaymentMethod: "Cheque",
  },
  {
    id: "8",
    Expense: "Blood Collection Tubes",
    Category: "Laboratory",
    Amount: "$450",
    Date: "09 Feb 2025",
    PurchasedBy: "Isabella Wilson",
    Status: "Approved",
    PaymentMethod: "PayPal",
  },
  {
    id: "9",
    Expense: "Bandages & Tapes",
    Category: "Medical Supplies",
    Amount: "$570",
    Date: "01 Feb 2025",
    PurchasedBy: "Michael Trade",
    Status: "New",
    PaymentMethod: "Debit Card",
  },
  {
    id: "10",
    Expense: "Tissue Slides",
    Category: "Laboratory",
    Amount: "$800",
    Date: "12 Jan 2025",
    PurchasedBy: "Ava Robinson",
    Status: "Approved",
    PaymentMethod: "Cheque",
  },
];
