export const HrmDepartmentsData = [
  {
    id: "1",
    Department: "Nursing",
    CreatedDate: "22 Apr 2025",
    NoofDoctor: "40",
    Status: "Active",
  },
  {
    id: "2",
    Department: "Pharmacy",
    CreatedDate: "12 Apr 2025",
    NoofDoctor: "15",
    Status: "Inactive",
  },
  {
    id: "3",
    Department: "Laboratory",
    CreatedDate: "01 Apr 2025",
    NoofDoctor: "10",
    Status: "Active",
  },
  {
    id: "4",
    Department: "Billing",
    CreatedDate: "05 Mar 2025",
    NoofDoctor: "13",
    Status: "Active",
  },
  {
    id: "5",
    Department: "Anesthesia",
    CreatedDate: "20 Mar 2025",
    NoofDoctor: "17",
    Status: "Active",
  },
  {
    id: "6",
    Department: "Administration",
    CreatedDate: "01 Mar 2025",
    NoofDoctor: "20",
    Status: "Active",
  },
  {
    id: "7",
    Department: "Counseling",
    CreatedDate: "15 Feb 2025",
    NoofDoctor: "25",
    Status: "Inactive",
  },
  {
    id: "8",
    Department: "Research",
    CreatedDate: "09 Feb 2025",
    NoofDoctor: "15",
    Status: "Active",
  },
  {
    id: "9",
    Department: "Biomedical",
    CreatedDate: "01 Feb 2025",
    NoofDoctor: "19",
    Status: "Active",
  },
  {
    id: "10",
    Department: "Rehabilitation",
    CreatedDate: "12 Jan 2025",
    NoofDoctor: "24",
    Status: "Active",
  },
];
