export const IncomeListData = [
  {
    IncomeName: "General Consultation",
    Amount: "$800",
    Date: "30 Apr 2025",
    Image: "user-01.jpg",
    ReceivedFrom: "James Carter",
    PaymentMethod: "PayPal",
    Status: "Received",
  },
  {
    IncomeName: "Blood Test",
    Amount: "$930",
    Date: "15 Apr 2025",
    Image: "user-02.jpg",
    ReceivedFrom: "Emily Johnson",
    PaymentMethod: "Debit Card",
    Status: "Pending",
  },
  {
    IncomeName: "MRI Scan",
    Amount: "$850",
    Date: "02 Apr 2025",
    Image: "user-03.jpg",
    ReceivedFrom: "Robert Mitchell",
    PaymentMethod: "Cheque",
    Status: "Received",
  },
  {
    IncomeName: "CT Scan",
    Amount: "$700",
    Date: "27 Mar 2025",
    Image: "user-04.jpg",
    ReceivedFrom: "Sophia Miller",
    PaymentMethod: "Debit Card",
    Status: "Received",
  },
  {
    IncomeName: "Allergy Panel",
    Amount: "$650",
    Date: "12 Mar 2025",
    Image: "user-05.jpg",
    ReceivedFrom: "Daniel Anderson",
    PaymentMethod: "PayPal",
    Status: "Pending",
  },
  {
    IncomeName: "PET Scan",
    Amount: "$430",
    Date: "05 Mar 2025",
    Image: "user-06.jpg",
    ReceivedFrom: "Olivia Davis",
    PaymentMethod: "Cheque",
    Status: "Received",
  },
  {
    IncomeName: "Orthopedic Checkup",
    Amount: "$300",
    Date: "24 Feb 2025",
    Image: "user-07.jpg",
    ReceivedFrom: "Michael Thompson",
    PaymentMethod: "Debit Card",
    Status: "Recerived",
  },
  {
    IncomeName: "Thyroid Test",
    Amount: "$450",
    Date: "16 Feb 2025",
    Image: "user-08.jpg",
    ReceivedFrom: "Isabella Wilson",
    PaymentMethod: "Cheque",
    Status: "Pending",
  },
  {
    IncomeName: "ENT Consultation",
    Amount: "$570",
    Date: "01 Feb 2025",
    Image: "user-09.jpg",
    ReceivedFrom: "Michael Trade",
    PaymentMethod: "Debit Card",
    Status: "Received",
  },
  {
    IncomeName: "Cataract Surgery",
    Amount: "$800",
    Date: "25 Jan 2025",
    Image: "user-10.jpg",
    ReceivedFrom: "Ava Robinson",
    PaymentMethod: "PayPal",
    Status: "Received",
  },
];