export const IcomeReportData = [
  {
    id: "1",
    Income: "Nurse",
    Amount: "$800",
    Date: "22 Apr 2025",
    ReceivedFrom: "James Carter",
    PaymentMethod: "PayPal",
    Status: "Received",
  },
  {
    id: "2",
    Income: "Pharmacist",
    Amount: "$930",
    Date: "12 Apr 2025",
    ReceivedFrom: "Emily Johnson",
    PaymentMethod: "Debit Card",
    Status: "Pending",
  },
  {
    id: "3",
    Income: "Receptionist",
    Amount: "$850",
    Date: "01 Apr 2025",
    ReceivedFrom: "Robert Mitchell",
    PaymentMethod: "Cheque",
    Status: "Received",
  },
  {
    id: "4",
    Income: "Technician",
    Amount: "$700",
    Date: "05 Mar 2025",
    ReceivedFrom: "Sophia Miller",
    PaymentMethod: "Cheque",
    Status: "Received",
  },
  {
    id: "5",
    Income: "Medical Assistant",
    Amount: "$650",
    Date: "20 Mar 2025",
    ReceivedFrom: "Daniel Anderson",
    PaymentMethod: "PayPal",
    Status: "Pending",
  },
  {
    id: "6",
    Income: "Phlebotomist",
    Amount: "$430",
    Date: "01 Mar 2025",
    ReceivedFrom: "Olivia Davis",
    PaymentMethod: "Debit Card",
    Status: "Received",
  },
  {
    id: "7",
    Income: "Dialysis Technician",
    Amount: "$300",
    Date: "15 Feb 2025",
    ReceivedFrom: "Michael Thompson",
    PaymentMethod: "Cheque",
    Status: "Received",
  },
  {
    id: "8",
    Income: "Medical Coder",
    Amount: "$450",
    Date: "09 Feb 2025",
    ReceivedFrom: "Isabella Wilson",
    PaymentMethod: "PayPal",
    Status: "Pending",
  },
  {
    id: "9",
    Income: "Chiropractor",
    Amount: "$570",
    Date: "01 Feb 2025",
    ReceivedFrom: "Michael Trade",
    PaymentMethod: "Debit Card",
    Status: "Received",
  },
  {
    id: "10",
    Income: "Acupuncturist",
    Amount: "$800",
    Date: "12 Jan 2025",
    ReceivedFrom: "Ava Robinson",
    PaymentMethod: "Cheque",
    Status: "Received",
  },
];
