export const PatientPescriptionsData = [
  {
    id: "1",
    Prescription_ID: "#PRE0025",
    Doctor_Name: "Dr. Mick Thompson ",
    img: "doctor-01.jpg",
    role: "Cardiologist",
    Prescribed_On: "30 Apr 2025",
  },
  {
    id: "2",
    Prescription_ID: "#PRE0024",
    Doctor_Name: "Dr. Sarah Johnson Orthopedic ",
    img: "doctor-02.jpg",
    role: "Surgeon",
    Prescribed_On: "15 Apr 2025",
  },
  {
    id: "3",
    Prescription_ID: "#PRE0023",
    Doctor_Name: "Dr. Emily Carter ",
    img: "doctor-03.jpg",
    role: "Pediatrician",
    Prescribed_On: "02 Apr 2025",
  },
  {
    id: "4",
    Prescription_ID: "#PRE0022",
    Doctor_Name: "Dr. David Lee ",
    img: "doctor-04.jpg",
    role: "Gynecologist",
    Prescribed_On: "27 Mar 2025",
  },
  {
    id: "5",
    Prescription_ID: "#PRE0021",
    Doctor_Name: "Dr. Anna Kim ",
    img: "doctor-05.jpg",
    role: "Psychiatrist",
    Prescribed_On: "12 Mar 2025",
  },
  {
    id: "6",
    Prescription_ID: "#PRE0020",
    Doctor_Name: "Dr. John Smith ",
    img: "doctor-06.jpg",
    role: "Neurosurgeon",
    Prescribed_On: "05 Mar 2025",
  },
  {
    id: "7",
    Prescription_ID: "#PRE0019",
    Doctor_Name: "Dr. Lisa White ",
    img: "doctor-07.jpg",
    role: "Oncologist",
    Prescribed_On: "24 Feb 2025",
  },
  {
    id: "8",
    Prescription_ID: "#PRE0018",
    Doctor_Name: "Dr. Patricia Brown ",
    img: "doctor-10.jpg",
    role: "Pulmonologist",
    Prescribed_On: "16 Feb 2025",
  },
  {
    id: "9",
    Prescription_ID: "#PRE0017",
    Doctor_Name: "Dr. Rachel Green ",
    img: "doctor-12.jpg",
    role: "Urologist",
    Prescribed_On: "01 Feb 2025",
  },
  {
    id: "10",
    Prescription_ID: "#PRE0016",
    Doctor_Name: "Dr. Michael Smith ",
    img: "doctor-15.jpg",
    role: "Cardiologist",
    Prescribed_On: "25 Jan 2025",
  },
];
