export const PatientAppoinmentsData = [
  {
    id: "1",
    Date_Time: "30 Apr 2025 - 09:30 AM",
    Doctor_Name: "Dr.Alberto Ripley",
    img: "doctor-01.jpg",
    role: "Cardiologist",
    Mode: "In-person",
    Status: "Checked Out",
  },
  {
    id: "2",
    Date_Time: "15 Apr 2025 - 11:20 AM",
    Doctor_Name: "Dr.Susan Babin",
    img: "doctor-02.jpg",
    role: " Orthopedic Surgeon",
    Mode: "Online",
    Status: "Checked In",
  },
  {
    id: "3",
    Date_Time: "02 Apr 2025 - 08:15 AM",
    Doctor_Name: "Dr.Carol Lam",
    img: "doctor-03.jpg",
    role: "Pediatrician",
    Mode: "In-Person",
    Status: "Cancelled",
  },
  {
    id: "4",
    Date_Time: "27 Mar 2025 - 02:00 PM",
    Doctor_Name: "Dr.Marsha Noland ",
    img: "doctor-04.jpg",
    role: "Gynecologist",
    Mode: "30 Apr 2025",
    Status: "Schedule",
  },
  {
    id: "5",
    Date_Time: "12 Mar 2025 - 05:40 PM",
    Doctor_Name: "Dr.Irma Armstrong ",
    img: "doctor-05.jpg",
    role: "Psychiatrist",
    Mode: "Online",
    Status: "Confirmed",
  },
  {
    id: "6",
    Date_Time: "24 Feb 2025 - 09:20 AM",
    Doctor_Name: "Dr.Ezra Belcher ",
    img: "doctor-06.jpg",
    role: "Neurosurgeon",
    Mode: "In-Person",
    Status: "Cancelled",
  },
  {
    id: "7",
    Date_Time: "16 Feb 2025 - 11:40 AM",
    Doctor_Name: "Dr.Glen Lentz ",
    img: "doctor-07.jpg",
    role: "Oncologist",
    Mode: "Online",
    Status: "Confirmed",
  },
  {
    id: "8",
    Date_Time: "01 Feb 2025 - 04:00 PM",
    Doctor_Name: "Dr.Bernard Griffith ",
    img: "doctor-08.jpg",
    role: "Pulmonologist",
    Mode: "Online",
    Status: "Checked Out",
  },
  {
    id: "9",
    Date_Time: "25 Jan 2025 - 03:10 PM",
    Doctor_Name: "Dr.John Elsass ",
    img: "doctor-09.jpg",
    role: "Urologist",
    Mode: "Online",
    Status: "Schedule",
  },
  {
    id: "10",
    Date_Time: "12 Jan 2025 - 03:10 PM",
    Doctor_Name: "Dr.John Albert ",
    img: "doctor-10.jpg",
    role: "Cardiologist",
    Mode: "In-Person",
    Status: "cancelled",
  },
];
