export const PatientReportData = [
  {
    id: "1",
    Patient: "Alberto Ripley",
    AgeGender: "26/Male",
    ContactInfo: "+1 43554 54584",
    Email: "james@example.com",
    Practioner: "Dr. Mick Thompson",
    Location: "California",
    LastVisit: "30 Apr 2025",
    Status: "Available",
  },
  {
    id: "2",
    Patient: "Susan Babin",
    AgeGender: "21/Female",
    ContactInfo: "+1 47554 54585",
    Email: "emily@example.com",
    Practioner: "Dr. Sarah Johnson",
    Location: "Texas",
    LastVisit: "15 Apr 2025",
    Status: "Unavailable",
  },
  {
    id: "3",
    Patient: "Carol Lam",
    AgeGender: "28/Male",
    ContactInfo: "+1 54114 54586",
    Email: "robert@example.com",
    Practioner: "Dr. Emily Carter",
    Location: "New York",
    LastVisit: "02 Apr 2025",
    Status: "Available",
  },
  {
    id: "4",
    Patient: "Marsha Noland",
    AgeGender: "25/Female",
    ContactInfo: "+1 51247 54587",
    Email: "sophia@example.com",
    Practioner: "Dr. David Lee",
    Location: "Florida",
    LastVisit: "27 Mar 2025",
    Status: "Unavailable",
  },
  {
    id: "5",
    Patient: "Irma Armstrong",
    AgeGender: "32/Male",
    ContactInfo: "+1 41452 54588",
    Email: "daniel@example.com",
    Practioner: "Dr. Anna Kim",
    Location: "Illinois",
    LastVisit: "12 Mar 2025",
    Status: "Available",
  },
  {
    id: "6",
    Patient: "Jesus Adams",
    AgeGender: "27/Female",
    ContactInfo: "+1 51425 54589",
    Email: "olivia@example.com",
    Practioner: "Dr. John Smith",
    Location: "Pennsylvania",
    LastVisit: "05 Mar 2025",
    Status: "Unavailable",
  },
  {
    id: "7",
    Patient: "Ezra Belcher",
    AgeGender: "28/Male",
    ContactInfo: "+1 42565 54590",
    Email: "michael@example.com",
    Practioner: "Dr. Lisa White",
    Location: "Ohio",
    LastVisit: "24 Feb 2025",
    Status: "Available",
  },
  {
    id: "8",
    Patient: "Glen Lentz",
    AgeGender: "22/Female",
    ContactInfo: "+1 51425 54589",
    Email: "isabella@example.com",
    Practioner: "Dr. Patricia Brown",
    Location: "Georgia",
    LastVisit: "16 Feb 2025",
    Status: "Unavailable",
  },
  {
    id: "9",
    Patient: "Bernard Griffith",
    AgeGender: "34/Male",
    ContactInfo: "+1 45214 54591",
    Email: "trade@example.com",
    Practioner: "Dr. Rachel Green",
    Location: "North Carolina",
    LastVisit: "01 Feb 2025",
    Status: "Available",
  },
  {
    id: "10",
    Patient: "John Elsass",
    AgeGender: "23/Female",
    ContactInfo: "+1 41245 54592",
    Email: "ava@example.com",
    Practioner: "Dr. Michael Smith",
    Location: "Michigan",
    LastVisit: "25 Jan 2025",
    Status: "Unavailable",
  },
];
