export const PatientDeatilsData = [
  {
    id: "1",
    Date_Time: "30 Apr 2026- 09:30 AM",
    Doctor_Name: "Dr. Mick Thompson ",
    Role: "Cardiologist",
    Doctor_Image: "doctor-01.jpg",
    Mode: "In-person",
    Status: "Checked Out",
  },
  {
    id: "2",
    Date_Time: "15 Apr 2026- 11:20 AM",
    Doctor_Name: "Dr. Sarah Johnson ",
    Role: "Orthopedic Surgeon",
    Doctor_Image: "doctor-02.jpg",
    Mode: "Online",
    Status: "Checked In",
  },
  {
    id: "3",
    Date_Time: "02 Apr 2026- 08:15 AM",
    Doctor_Name: "Dr. Emily Carter ",
    Role: "Pediatrician",
    Doctor_Image: "doctor-03.jpg",
    Mode: "In-Person",
    Status: "Cancelled",
  },
  {
    id: "4",
    Date_Time: "27 Mar 2026- 02:00 PM",
    Doctor_Name: "Dr. David Lee Gynecologist",
    Role: "Gynecologist",
    Doctor_Image: "doctor-04.jpg",
    Mode: "In-person",
    Status: "Schedule",
  },
  {
    id: "5",
    Date_Time: "12 Mar 2026- 05:40 PM",
    Doctor_Name: "Dr. Anna Kim ",
    Role: "Psychiatrist",
    Doctor_Image: "doctor-05.jpg",
    Mode: "Online",
    Status: "Confirmed",
  },
  {
    id: "6",
    Date_Time: "24 Feb 2026- 09:20 AM",
    Doctor_Name: "Dr. John Smith ",
    Role: "Neurosurgeon",
    Doctor_Image: "doctor-06.jpg",
    Mode: "In-Person",
    Status: "Cancelled",
  },
  {
    id: "7",
    Date_Time: "16 Feb 2026- 11:40 AM",
    Doctor_Name: "Dr. Lisa White ",
    Role: "Oncologist",
    Doctor_Image: "doctor-07.jpg",
    Mode: "Online",
    Status: "Confirmed",
  },
  {
    id: "8",
    Date_Time: "01 Feb 2026- 04:00 PM",
    Doctor_Name: "Dr. Patricia Brown ",
    Role: "Pulmonologist",
    Doctor_Image: "doctor-08.jpg",
    Mode: "Online",
    Status: "Checked Out",
  },
  {
    id: "9",
    Date_Time: "25 Jan 2026- 03:10 PM",
    Doctor_Name: "Dr. Rachel Green ",
    Role: "Urologist",
    Doctor_Image: "doctor-09.jpg",
    Mode: "Online",
    Status: "Schedule",
  },
  {
    id: "10",
    Date_Time: "12 Jan 2026- 03:10 PM",
    Doctor_Name: "Dr. Michael Smith ",
    Role: "Cardiologist",
    Doctor_Image: "doctor-10.jpg",
    Mode: "In-Person",
    Status: "cancelled",
  },
];
