export const PatientListData = [
  {
    id: "1",
    Patient: "Alberto Ripley",
    Gender: "26, Male",
    Patient_img: "user-08.jpg",
    Doctor_img: "doctor-01.jpg",
    Phone: "+1 41245 54132",
    Doctor: "Dr. Mick Thompson ",
    Role: "Cardiologist",
    Address: "Miami, Florida",
    Last_Visit: "30 Apr 2025",
    Status: "Available",
  },
  {
    id: "2",
    Patient: "Susan Babin  21, Female",
    Gender: "21, Female",
    Patient_img: "user-16.jpg",
    Doctor_img: "doctor-02.jpg",
    Phone: "+1 54554 54789",
    Doctor: "Dr. Sarah Johnson ",
    Role: "Orthopedic Surgeon",
    Address: "Austin, Texas",
    Last_Visit: "15 Apr 2025",
    Status: "Unavailable",
  },
  {
    id: "3",
    Patient: "Carol Lam  ",
    Gender: "28, Female",
    Patient_img: "user-06.jpg",
    Doctor_img: "doctor-03.jpg",
    Phone: "+1  43554 54985",
    Doctor: "Dr. Emily Carter ",
    Role: "Pediatrician",
    Address: "Seattle, Washington",
    Last_Visit: "02 Apr 2025",
    Status: "Available",
  },
  {
    id: "4",
    Patient: "Marsha Noland  ",
    Gender: "25, Female",
    Patient_img: "user-25.jpg",
    Doctor_img: "doctor-04.jpg",
    Phone: "+1 47554 54257",
    Doctor: "Dr. David Lee ",
    Role: "Gynecologist",
    Address: "Chicago, Illinois",
    Last_Visit: "27 Mar 2025",
    Status: "Unavailable",
  },
  {
    id: "5",
    Patient: "Irma Armstrong  ",
    Gender: "32, Female",
    Patient_img: "user-39.jpg",
    Doctor_img: "doctor-05.jpg",
    Phone: "+1 54114 57526",
    Doctor: "Dr. Anna Kim ",
    Role: "Psychiatrist",
    Address: "Phoenix, Arizona",
    Last_Visit: "12 Mar 2025",
    Status: "Available",
  },
  {
    id: "6",
    Patient: "Jesus Adams ",
    Gender: "27, Male",
    Patient_img: "user-14.jpg",
    Doctor_img: "doctor-06.jpg",
    Phone: "+1 51247 56574",
    Doctor: "Dr. John Smith ",
    Role: "Neurosurgeon",
    Address: "Atlanta, Georgia",
    Last_Visit: "05 Mar 2025",
    Status: "Unavailable",
  },
  {
    id: "7",
    Patient: "Ezra Belcher ",
    Gender: "28, Male",
    Patient_img: "user-27.jpg",
    Doctor_img: "doctor-07.jpg",
    Phone: "+1 41452 25741",
    Doctor: "Dr. Lisa White ",
    Role: "Oncologist",
    Address: "San Diego, California",
    Last_Visit: "24 Feb 2025",
    Status: "Available",
  },
  {
    id: "8",
    Patient: "Glen Lentz  ",
    Gender: "22, Male",
    Patient_img: "user-05.jpg",
    Doctor_img: "doctor-08.jpg",
    Phone: "+1 51425 21498",
    Doctor: "Dr. Patricia Brown ",
    Role: "Pulmonologist",
    Address: "Denver, Colorado",
    Last_Visit: "16 Feb 2025",
    Status: "Unavailable",
  },
  {
    id: "9",
    Patient: "Bernard Griffith  ",
    Gender: "34, Male",
    Patient_img: "user-07.jpg",
    Doctor_img: "doctor-09.jpg",
    Phone: "+1 45214 98741",
    Doctor: "Dr. Rachel Green ",
    Role: "Urologist",
    Address: "Boston, Massachusetts",
    Last_Visit: "01 Feb 2025",
    Status: "Available",
  },
  {
    id: "10",
    Patient: "John Elsass  ",
    Gender: "23, Male",
    Patient_img: "user-17.jpg",
    Doctor_img: "doctor-10.jpg",
    Phone: "+1 41245 32540",
    Doctor: "Dr. Michael Smith ",
    Role: "Cardiologist",
    Address: "Orlando, Florida",
    Last_Visit: "25 Jan 2025",
    Status: "Unavailable",
  },
];
