export const PaymentsListData = [
  {
    InvoiceID: "#INV0025",
    Patient: "James Adair",
    Image: "user-01.jpg",
    DoctorImage: "doctor-01.jpg",
    Doctor: "Dr. Anna Kim",
    Position: "Psychiatrist",
    PaidDate: "30 Apr 2025",
    Amount: "$800",
    PaymentMethod: "PayPal",
    Status: "Paid",
  },
  {
    InvoiceID: "#INV0024",
    Patient: "Emily Johnson",
    Image: "user-02.jpg",
    DoctorImage: "doctor-02.jpg",
    Doctor: "Dr.Sarah Johnson",
    Position: "Orthopedic Surgeon",
    PaidDate: "15 Apr 2025",
    Amount: "$930",
    PaymentMethod: "Debit Card",
    Status: "Partially Paid",
  },
  {
    InvoiceID: "#INV0023",
    Patient: "Robert Mitchell",
    Image: "user-03.jpg",
    DoctorImage: "doctor-03.jpg",
    Doctor: "Dr.Emily Carter",
    Position: "Pediatrician",
    PaidDate: "02 Apr 2025",
    Amount: "$850",
    PaymentMethod: "Cheque",
    Status: "Unpaid",
  },
  {
    InvoiceID: "#INV0022",
    Patient: "Sophia Miller",
    Image: "user-04.jpg",
    DoctorImage: "doctor-04.jpg",
    Doctor: "Dr.David Lee",
    Position: "Gynecologist",
    PaidDate: "27 Mar 2025",
    Amount: "$700",
    PaymentMethod: "Debit Card",
    Status: "Paid",
  },
  {
    InvoiceID: "#INV0021",
    Patient: "Daniel Anderson",
    Image: "user-05.jpg",
    DoctorImage: "doctor-05.jpg",
    Doctor: "Dr.Anna Kim",
    Position: "Psychiatrist",
    PaidDate: "12 Mar 2025",
    Amount: "$650",
    PaymentMethod: "PayPal",
    Status: "Partially Paid",
  },
  {
    InvoiceID: "#INV0020",
    Patient: "Olivia Davis",
    Image: "user-06.jpg",
    DoctorImage: "doctor-06.jpg",
    Doctor: "Dr. John Smith",
    Position: "Neurosurgeon",
    PaidDate: "05 Mar 2025",
    Amount: "$430",
    PaymentMethod: "Cheque",
    Status: "Unpaid",
  },
  {
    InvoiceID: "#INV0019",
    Patient: "Michael Thompson",
    Image: "user-07.jpg",
    DoctorImage: "doctor-07.jpg",
    Doctor: "Dr.Lisa White",
    Position: "Oncologist",
    PaidDate: "24 Feb 2025",
    Amount: "$300",
    PaymentMethod: "Debit Card",
    Status: "Paid",
  },
  {
    InvoiceID: "#INV0018",
    Patient: "Isabella Wilson",
    Image: "user-08.jpg",
    DoctorImage: "doctor-08.jpg",
    Doctor: "Dr. Patricia Brown",
    Position: "Pulmonologist",
    PaidDate: "16 Feb 2025",
    Amount: "$450",
    PaymentMethod: "Cheque",
    Status: "Unpaid",
  },
  {
    InvoiceID: "#INV0017",
    Patient: "Michael Trade",
    Image: "user-09.jpg",
    DoctorImage: "doctor-09.jpg",
    Doctor: "Dr. Rachel Green",
    Position: "Urologist",
    PaidDate: "01 Feb 2025",
    Amount: "$570",
    PaymentMethod: "Debit Card",
    Status: "Paid",
  },
  {
    InvoiceID: "#INV0016",
    Patient: "Ava Robinson",
    Image: "user-10.jpg",
    DoctorImage: "doctor-10.jpg",
    Doctor: "Dr.Michael Smith",
    Position: "Cardiologist",
    PaidDate: "25 Jan 2025",
    Amount: "$800",
    PaymentMethod: "PayPal",
    Status: "Unpaid",
  },
]