export const PayrollListData = [
  {
    id:"1",
    Employee: "James Adair",
    Image: "user-08.jpg",
    Email: "james@gmail.com",
    JoiningDate: "01 Jan 2024",
    Role: "Admin",
    Salary: "$1200",
    Status: "Generate Slip",
  },
  {
    id:"2",
    Employee: "Adam Milne",
    Image: "user-03.jpg",
    Email: "esther@gmail.com",
    JoiningDate: "04 Jan 2023",
    Role: "Reception",
    Salary: "$2000",
    Status: "Generate Slip",
  },
  {
    id:"3",
    Employee: "Richard Clark",
    Image: "user-04.jpg",
    Email: "judi@gmail.com",
    JoiningDate: "26 Jan 2022",
    Role: "Admin",
    Salary: "$1500",
    Status: "Generate Slip",
  },
  {
    id:"4",
    Employee: "Robert Reid",
    Image: "user-05.jpg",
    Email: "robert@gmail.com",
    JoiningDate: "04 Feb 2022",
    Role: "Admin",
    Salary: "$1200",
    Status: "Generate Slip",
  },
  {
    id:"5",
    Employee: "Dottie Jeny",
    Image: "user-06.jpg",
    Email: "dottie@gmail.com",
    JoiningDate: "03 Mar 2021",
    Role: "Nurse",
    Salary: "$1500",
    Status: "Generate Slip",
  },
  {
    id:"6",
    Employee: "Cheryl Bilodeau",
    Image: "user-07.jpg",
    Email: "cheryl@gmail.com",
    JoiningDate: "08 May 2021",
    Role: "Nurse (RN)",
    Salary: "$2500",
    Status: "Generate Slip",
  },
  {
    id:"7",
    Employee: "Valerie Padgett",
    Image: "user-02.jpg",
    Email: "valerie@gmail.com",
    JoiningDate: "29 Mar 2021",
    Role: "Nurse Practitioner",
    Salary: "$1000",
    Status: "Generate Slip",
  },
  {
    id:"8",
    Employee: "Diane Nash",
    Image: "user-25.jpg",
    Email: "diane@gmail.com",
    JoiningDate: "01 Apr 2020",
    Role: "Nurse",
    Salary: "$1250",
    Status: "Generate Slip",
  },
  {
    id:"9",
    Employee: "Sally Cavazos",
    Image: "user-29.jpg",
    Email: "sally@gmail.com",
    JoiningDate: "01 May 2020",
    Role: "Nurse",
    Salary: "$1550",
    Status: "Generate Slip",
  },
  {
    id:"10",
    Employee: "Forest Heath",
    Image: "user-12.jpg",
    Email: "forest@gmail.com",
    JoiningDate: "27 May 2020",
    Role: "Reception",
    Salary: "$1250",
    Status: "Generate Slip",
  },
];
