export const ServiceListData = [
  {
    id:"1",
    ServiceName: "General Consultation",
    Department: "General Medicine",
    Price: "$200",
    Status: "Active",
  },
  {
    id:"2",
    ServiceName: "Dental Cleaning",
    Department: "Dentistry",
    Price: "$180",
    Status: "Inactive",
  },
  {
    id:"3",
    ServiceName: "Eye Checkup",
    Department: "Ophthalmology",
    Price: "$150",
    Status: "Active",
  },
  {
    id:"4",
    ServiceName: "X-Ray",
    Department: "Radiology",
    Price: "$80",
    Status: "Active",
  },
  {
    id:"5",
    ServiceName: "Physiotherapy Session",
    Department: "Physiotherapy",
    Price: "$130",
    Status: "Active",
  },
  {
    id:"6",
    ServiceName: "Cardiac Screening",
    Department: "Cardiology",
    Price: "$300",
    Status: "Active",
  },
  {
    id:"7",
    ServiceName: "Skin Allergy Test",
    Department: "Dermatology",
    Price: "$220",
    Status: "Inactive",
  },
  {
    id:"8",
    ServiceName: "Blood Test",
    Department: "Pathology",
    Price: "$150",
    Status: "Active",
  },
  {
    id:"9",
    ServiceName: "ENT Consultation",
    Department: "ENT",
    Price: "$230",
    Status: "Active",
  },
  {
    id:"10",
    ServiceName: "Nutrition Counseling",
    Department: "Nutrition",
    Price: "$250",
    Status: "Active",
  },
];
