export const SpecializationsListData = [
  {
    id: "1",
    Specialization: "General Medicine",
    img: "specialization-01.jpg",
    CreatedDate: "22 Apr 2025",
    NoofDoctor: "20",
    Image: "specialization-01.jpg",
    Status: "Active",
  },
  {
    id: "2",
    Specialization: "Dentistry",
    img: "specialization-02.jpg",
    CreatedDate: "12 Apr 2025",
    NoofDoctor: "15",
    Image: "specialization-02.jpg",
    Status: "Inactive",
  },
  {
    id: "3",
    Specialization: "Ophthalmology",
    img: "specialization-03.jpg",
    CreatedDate: "01 Apr 2025",
    NoofDoctor: "10",
    Image: "specialization-03.jpg",
    Status: "Active",
  },
  {
    id: "4",
    Specialization: "Radiology",
    img: "specialization-04.jpg",
    CreatedDate: "05 Mar 2025",
    NoofDoctor: "13",
    Image: "specialization-04.jpg",
    Status: "Active",
  },
  {
    id: "5",
    Specialization: "Physiotherapy",
    img: "specialization-05.jpg",
    CreatedDate: "20 Mar 2025",
    NoofDoctor: "17",
    Image: "specialization-05.jpg",
    Status: "Active",
  },
  {
    id: "6",
    Specialization: "Cardiology",
    img: "specialization-06.jpg",
    CreatedDate: "01 Mar 2025",
    NoofDoctor: "20",
    Image: "specialization-06.jpg",
    Status: "Active",
  },
  {
    id: "7",
    Specialization: "Dermatology",
    img: "specialization-07.jpg",
    CreatedDate: "15 Feb 2025",
    NoofDoctor: "25",
    Image: "specialization-07.jpg",
    Status: "Inactive",
  },
  {
    id: "8",
    Specialization: "Pathology",
    img: "specialization-08.jpg",
    CreatedDate: "09 Feb 2025",
    NoofDoctor: "15",
    Image: "specialization-08.jpg",
    Status: "Active",
  },
  {
    id: "9",
    Specialization: "ENT",
    img: "specialization-09.jpg",
    CreatedDate: "01 Feb 2025",
    NoofDoctor: "19",
    Image: "specialization-09.jpg",
    Status: "Active",
  },
  {
    id: "10",
    Specialization: "Nutrition",
    img: "specialization-10.jpg",
    CreatedDate: "12 Jan 2025",
    NoofDoctor: "24",
    Image: "specialization-10.jpg",
    Status: "Active",
  },
];
