export const StaffsListData = [
  {
    id: "1",
    Staff: "James Adair",
    Image: "user-08.jpg",
    Designation: "Admin Officer",
    Role: "Admin",
    Phone: "+1 41245 54132",
    Email: "james@gmail.com",
    Status: "Available",
  },
  {
    id: "2",
    Staff: "Adam Milne",
    Image: "user-03.jpg",
    Designation: "Front Officer",
    Role: "Reception",
    Phone: "+1 54554 54789",
    Email: "adam@gmail.com",
    Status: "Available",
  },
  {
    id: "3",
    Staff: "Richard Clark",
    Image: "user-04.jpg",
    Designation: "Medical Recorder",
    Role: "Admin",
    Phone: "+1 43554 54985",
    Email: "richard@gmail.com",
    Status: "Unavailable",
  },
  {
    id: "4",
    Staff: "Robert Reid",
    Image: "user-05.jpg",
    Designation: "Billing Executive",
    Role: "Admin",
    Phone: "+1 47554 54257",
    Email: "robert@gmail.com",
    Status: "Available",
  },
  {
    id: "5",
    Staff: "Dottie Jeny",
    Image: "user-06.jpg",
    Designation: "Nurse",
    Role: "Nurse",
    Phone: "+1 54114 57526",
    Email: "dottie@gmail.com",
    Status: "Available",
  },
  {
    id: "6",
    Staff: "Cheryl Bilodeau",
    Image: "user-07.jpg",
    Designation: "Staff Nurse",
    Role: "Nurse (RN)",
    Phone: "+1 51247 56574",
    Email: "cheryl@gmail.com",
    Status: "Available",
  },
  {
    id: "7",
    Staff: "Valerie Padgett",
    Image: "user-02.jpg",
    Designation: "HR Executive",
    Role: "Nurse Practitioner",
    Phone: "+1 41452 25741",
    Email: "valerie@gmail.com",
    Status: "Available",
  },
  {
    id: "8",
    Staff: "Diane Nash",
    Image: "user-25.jpg",
    Designation: "Nurse Specialist",
    Role: "Nurses",
    Phone: "+1 51425 21498",
    Email: "diane@gmail.com",
    Status: "Available",
  },
  {
    id: "9",
    Staff: "Sally Cavazos",
    Image: "user-29.jpg",
    Designation: "Nurse Specialist",
    Role: "Nurses",
    Phone: "+1 45214 98741",
    Email: "sally@gmail.com",
    Status: "Available",
  },
  {
    id: "10",
    Staff: "Forest Heath",
    Image: "user-12.jpg",
    Designation: "Call Center",
    Role: "Reception",
    Phone: "+1 41245 32540",
    Email: "forest@gmail.com",
    Status: "Available",
  },
];
