export const StateData = [
  {
    id: "1",
    Country_Code: "US",
    img: "us.svg",
    Country: "USA",
    State: "California",
    Status: "Active",
  },
  {
    id: "2",
    Country_Code: "CA",
    img: "ca.svg",
    Country: "Canada",
    State: "Ontario",
    Status: "Active",
  },
  {
    id: "3",
    Country_Code: "UK",
    img: "uk.svg",
    Country: "UK",
    State: "England",
    Status: "Active",
  },
  {
    id: "4",
    Country_Code: "DE",
    img: "de.svg",
    Country: "Germany",
    State: "Bavaria",
    Status: "Active",
  },
  {
    id: "5",
    Country_Code: "FR",
    img: "fr.svg",
    Country: "France",
    State: "Le-de-France",
    Status: "Active",
  },
  {
    id: "6",
    Country_Code: "AR",
    img: "ar.svg",
    Country: "Argentina",
    State: "Buenos Aires",
    Status: "Active",
  },
  {
    id: "7",
    Country_Code: "IN",
    img: "in.svg",
    Country: "India",
    State: "Tamil Nadu",
    Status: "Active",
  },
  {
    id: "8",
    Country_Code: "IT",
    img: "it.svg",
    Country: "Italy",
    State: "Lombardy",
    Status: "Active",
  },
  {
    id: "9",
    Country_Code: "NZ",
    img: "nz.svg",
    Country: "New Zealand",
    State: "Wellington",
    Status: "Inactive",
  },
  {
    id: "10",
    Country_Code: "AU",
    img: "au.svg",
    Country: "Australia",
    State: "New South Wales",
    Status: "Inactive",
  },
];
