export const TicketsListData = [
  {
    id: "1",
    TicketID: "#TKT020",
    CreatedBy: "Alberto Ripley",
    Image: "user-33.jpg",
    Subject: "Scheduling Error",
    CreatedDate: "30 Apr 2025",
    Priority: "Low",
    Assignee: "IT Team",
    Status: "Resolved",
  },
  {
    id: "2",
    TicketID: "#TKT019",
    CreatedBy: "Susan Babin",
    Image: "user-01.jpg",
    Subject: "Lab Upload Issue",
    CreatedDate: "15 Apr 2025",
    Priority: "High",
    Assignee: "Lab Technician",
    Status: "Inprogress",
  },
  {
    id: "3",
    TicketID: "#TKT018",
    CreatedBy: "Carol Lam",
    Image: "user-02.jpg",
    Subject: "Auto Logout Complaint",
    CreatedDate: "02 Apr 2025",
    Priority: "Medium",
    Assignee: "System Admin",
    Status: "Open",
  },
  {
    id: "4",
    TicketID: "#TKT017",
    CreatedBy: "Marsha Noland",
    Image: "user-04.jpg",
    Subject: "Mobile View Problem",
    CreatedDate: "27 Mar 2025",
    Priority: "Low",
    Assignee: "EHR Support Team",
    Status: "Closed",
  },
  {
    id: "5",
    TicketID: "#TKT016",
    CreatedBy: "Irma Armstrong",
    Image: "user-05.jpg",
    Subject: "Performance Degradation",
    CreatedDate: "12 Mar 2025",
    Priority: "High",
    Assignee: "IT Team",
    Status: "Resolved",
  },
  {
    id: "6",
    TicketID: "#TKT015",
    CreatedBy: "Jesus Adams",
    Image: "user-07.jpg",
    Subject: "Role Assignment Bug",
    CreatedDate: "05 Mar 2025",
    Priority: "Medium",
    Assignee: "Admin Panel Support",
    Status: "Inprogress",
  },
  {
    id: "7",
    TicketID: "#TKT014",
    CreatedBy: "Ezra Belcher",
    Image: "user-08.jpg",
    Subject: "Reminder Failure",
    CreatedDate: "19 Feb 2025",
    Priority: "Low",
    Assignee: "Communications Specialist",
    Status: "Open",
  },
  {
    id: "8",
    TicketID: "#TKT013",
    CreatedBy: "Glen Lentz",
    Image: "user-10.jpg",
    Subject: "Incorrect Date Format",
    CreatedDate: "16 Feb 2025",
    Priority: "High",
    Assignee: "QA Department",
    Status: "Closed",
  },
  {
    id: "9",
    TicketID: "#TKT012",
    CreatedBy: "Bernard Griffith",
    Image: "user-12.jpg",
    Subject: "Invoice Calculation Error",
    CreatedDate: "01 Feb 2025",
    Priority: "Medium",
    Assignee: "Accountant",
    Status: "Resolved",
  },
  {
    id: "10",
    TicketID: "#TKT011",
    CreatedBy: "John Elsass",
    Image: "user-14.jpg",
    Subject: "File Upload Blocked",
    CreatedDate: "20 Jas 2025",
    Priority: "Low",
    Assignee: "Patient Portal Support",
    Status: "Inprogress",
  },
];
