export const TransactionsListData = [
  {
    TransactionID: "#TNX0025",
    Patient: "James Adair",
    Image: "user-01.jpg",
    Description: "General Consultation",
    PaidDate: "30 Apr 2025",
    PaymentMethod: "PayPal",
    Amount: "$800",
    Status: "Completed",
  },
  {
    TransactionID: "#TNX0024",
    Patient: "Emily Johnson",
    Image: "user-02.jpg",
    Description: "Dental Cleaning",
    PaidDate: "15 Apr 2025",
    PaymentMethod: "Debit Card",
    Amount: "$930",
    Status: "Pending",
  },
  {
    TransactionID: "#TNX0023",
    Patient: "Robert Mitchell",
    Image: "user-03.jpg",
    Description: "Eye Checkup",
    PaidDate: "02 Apr 2025",
    PaymentMethod: "Cheque",
    Amount: "$850",
    Status: "Completed",
  },
  {
    TransactionID: "#TNX0022",
    Patient: "Sophia Miller",
    Image: "user-04.jpg",
    Description: "X-Ray",
    PaidDate: "27 Mar 2025",
    PaymentMethod: "Debit Card",
    Amount: "$80",
    Status: "Completed",
  },
  {
    TransactionID: "#TNX0021",
    Patient: "Daniel Anderson",
    Image: "user-05.jpg",
    Description: "Physiotherapy Session",
    PaidDate: "12 Mar 2025",
    PaymentMethod: "PayPal",
    Amount: "$650",
    Status: "Completed",
  },
  {
    TransactionID: "#TNX0020",
    Patient: "Olivia Davis",
    Image: "user-06.jpg",
    Description: "Cardiac Screening",
    PaidDate: "05 Mar 2025",
    PaymentMethod: "Cheque",
    Amount: "$430",
    Status: "Completed",
  },
  {
    TransactionID: "#TNX0019",
    Patient: "Michael Thompson",
    Image: "user-07.jpg",
    Description: "Skin Allergy Test",
    PaidDate: "24 Feb 2025",
    PaymentMethod: "Debit Card",
    Amount: "$300",
    Status: "Pending",
  },
  {
    TransactionID: "#TNX0018",
    Patient: "Isabella Wilson",
    Image: "user-08.jpg",
    Description: "Blood Test",
    PaidDate: "16 Feb 2025",
    PaymentMethod: "Cheque",
    Amount: "$450",
    Status: "Completed",
  },
  {
    TransactionID: "#TNX0017",
    Patient: "Michael Trade",
    Image: "user-09.jpg",
    Description: "ENT Consultation",
    PaidDate: "01 Feb 2025",
    PaymentMethod: "Debit Card",
    Amount: "$570",
    Status: "Completed",
  },
  {
    TransactionID: "#TNX0017",
    Patient: "Ava Robinson",
    Image: "user-10.jpg",
    Description: "Nutrition Counseling",
    PaidDate: "25 Jan 2025",
    PaymentMethod: "PayPal",
    Amount: "$800",
    Status: "Completed",
  },
]